.github/workflows/tests.yml
.gitmodules
CHANGELOG.md
README.rst
cli/cmd/rocks.go
cli/cmd/root.go
cli/rocks/extra/hardcoded.lua
cli/rocks/extra/wrapper.lua
cli/rocks/rocks.go
go.mod
go.sum
test/integration/rocks/test_rocks.py

Add LuaRocks module. LuaRocks embed with Gopher-Lua and embed.FS
features.
Close #14

add tt rocks module

---

cli/configure/configure_test.go

Before testing configure, file "tt" is being deleted
from tmp if it exists.
Close #52

test: add cleanup for tmp before configure test

---

CHANGELOG.md
README.rst
cli/cmd/crud.go
cli/cmd/root.go
cli/codegen/generate_code.go
cli/crud/dump.go
cli/crud/import.go
cli/crud/lua/import.lua
cli/crud/print.go
cli/crud/router.go
cli/crud/types.go
cli/ttparsers/ttcsv.go

Add a module responsible for importing the contents from file to Tarantool via crud.
Closes #35

Add tt crud-import module

---

.github/workflows/tests.yml
README.rst
cli/cmd/cat.go
cli/cmd/completion.go
cli/cmd/connect.go
cli/cmd/help.go
cli/cmd/play.go
cli/cmd/root.go
cli/configure/configure.go
cli/connect/console.go
cli/connector/binary.go
cli/connector/connector.go
cli/connector/eval_plain_text.go
cli/connector/plain_text.go
cli/modules/modules.go
cli/modules/run.go
cli/running/instance_test.go
cli/ttparsers/ttcsv.go
cli/util/util.go
golangci-lint.yml
magefile.go

In golang we must use maximum line length up to 100 characters.

lint: adjusted line length to 100 characters

---

CHANGELOG.md
README.rst
cli/cmd/cat.go
cli/cmd/check.go
cli/cmd/completion.go
cli/cmd/connect.go
cli/cmd/help.go
cli/cmd/logrotate.go
cli/cmd/play.go
cli/cmd/restart.go
cli/cmd/rocks.go
cli/cmd/root.go
cli/cmd/run.go
cli/cmd/start.go
cli/cmd/status.go
cli/cmd/stop.go
cli/cmd/version.go
cli/cmdcontext/cmdcontext.go
cli/running/instance.go
cli/running/lua/launcher.lua
cli/running/run_test.go
cli/running/running.go
cli/running/test_app/dumb_test_run.lua
go.mod
test/integration/run/test_app/test_app.lua
test/integration/run/test_run.py

Added module to start instances without watchdog.
Closes #29

tt: add tt run module

---

.gitmodules

Part of https://github.com/tarantool/security/issues/12

rocks: switch luarocks module to 3.1.3 branch

---

cli/cmd/root.go
cli/main.go

In this patch the ability to inject the additional commands to the root has been added.

Prepare to integration with tt-ee

---

CHANGELOG.md
README.rst
cli/cmd/root.go
cli/cmd/search.go
cli/search/search.go
test/integration/search/test_search.py

Added search module to to show available tt/tarantool versions.
Closes #95

Add search module

---

magefile.go

The old patching system had an incorrect
check that patches had already been applied.

cartridge: patching mechanism fixes

---

.codespellrc
.github/workflows/tests.yml
README.rst
cli/checkpoint/lua/cat.lua
cli/checkpoint/lua/play.lua
cli/cmd/cat.go
cli/cmd/play.go
cli/cmd/search.go
cli/configure/configure.go
cli/connect/console.go
cli/connector/eval_plain_text.go
cli/coredump/coredump.go
cli/modules/modules.go
cli/running/lua/check.lua
cli/running/lua/launcher.lua
cli/running/watchdog.go
cli/util/util.go
magefile.go
test/integration/cli/test_launch.py
test/integration/play/test_file/remote_instance_cfg.lua
test/integration/search/test_search.py
test/requirements.txt

All typos was found with `codespell`

ci: add codespell

---

cli/cmd/create.go
test/integration/create/test_create.py

Added checking for presense of template name argument.

tt: added check for required argument

---

magefile.go

The patching system can now distinguish between an error and the fact that a patch has already been applied.
Also, the output is now printed only after the patch has been applied.

cartridge cli: improved patching system

---

CHANGELOG.md
README.rst
cli/build/build.go
cli/build/build_test.go
cli/build/local.go
cli/build/local_test.go
cli/build/testdata/app1/app1-scm-1.rockspec
cli/build/testdata/app1/app1-scm-2.rockspec
cli/build/testdata/runhooks/cartridge.post-build
cli/build/testdata/runhooks/cartridge.pre-build
cli/build/testdata/runhooks/tt.post-build
cli/build/testdata/runhooks/tt.pre-build
cli/cmd/build.go
cli/cmd/root.go
cli/cmdcontext/cmdcontext.go
cli/util/execute.go
cli/util/util.go
test/integration/build/apps/app1/app1-scm-1.rockspec
test/integration/build/apps/app1/app1-scm-2.rockspec
test/integration/build/apps/cartridge_hooks/cartridge.post-build
test/integration/build/apps/cartridge_hooks/cartridge.pre-build
test/integration/build/apps/tt_hooks/tt.post-build
test/integration/build/apps/tt_hooks/tt.pre-build
test/integration/build/test_build.py

Added build module with local build implementation. --spec option is supported to specify rockspec file to use.
Closes #40

build: added build module

---

.github/workflows/tests.yml
CHANGELOG.md
README.rst
cli/cmd/install.go
cli/cmd/remove.go
cli/cmd/root.go
cli/cmd/search.go
cli/config/config.go
cli/configure/configure.go
cli/configure/configure_test.go
cli/install/install.go
cli/install_ee/install_ee.go
cli/install_ee/install_ee_test.go
cli/remove/remove.go
cli/search/search.go
cli/util/util.go
cli/version/version_tools.go
cli/version/version_tools_test.go
test/integration/cli/test_launch.py
test/integration/install/test_install.py
test/integration/remove/test_remove.py
test/integration/search/test_search.py

Added install and remove modules.
Closes #94, #91, #92

tt: install and remove modules

---

cli/search/search.go

This patch adds printing of the [installed] mark if version installed.
Example:
$ tt search tarantool
...
2.10.0-rc1
2.10.0
2.10.1
2.10.2
2.11.0-entrypoint [installed]
master
Closes #146

search: add label for installed programs

---

doc/examples.rst

doc: small changes in the example

---

cli/running/running.go
test/integration/running/multi_inst_app/init.lua
test/integration/running/multi_inst_app/instances.yml
test/integration/running/multi_inst_app/router.init.lua
test/integration/running/multi_inst_app/tarantool.yaml
test/integration/running/test_running.py

Added support of start/stop application in current directory. If application name passed to start/stop command is equal to current directory name, current directory is considered as application.

tt: support application in current dir

---

cli/pack/common.go

Here is the result of empty app integration test:
```
• Apps to pack: empty_app  
2022/10/17 12:23:12 Whoops! It looks like something is wrong with this version of Tarantool CLI.
Error: Unhandled internal error: runtime error: invalid memory address or nil pointer dereference
Version: Tarantool CLI version 0.1.0, linux/amd64. commit: 2520a4f
```
If empty directory name is specified in app-list option, this app list is not checked if the specified app names are real applications. The solutions is to add these check and skip directories that are not apps.

pack: fix empty app pack crash

---

CHANGELOG.md
README.rst
cli/cmd/init.go
cli/cmd/root.go
cli/cmdcontext/cmdcontext.go
cli/configure/configure.go
cli/configure/configure_test.go
cli/init/init.go
cli/init/init_test.go
cli/init/testdata/invalid_cartridge.yml
cli/init/testdata/valid_cartridge.yml
cli/init/testdata/wrong_data_format.yml
test/integration/init/configs/valid_cartridge.yml
test/integration/init/test_init.py

init: implemented init for cartridge app

---

cli/install/install.go
test/integration/install/test_install.py

Fix for ignoring tt installation version.

install: fix tt install

---

.gen_tarballs.sh
.github/workflows/publish.yml
.goreleaser.yml
magefile.go
magefile.publish.go
tarantool.yaml.default

Added CI workflow to build and publish RPM and DEB packages to RWS.
Closes #110

ci: add publish workflow

---

.github/workflows/publish.yml

cd: fix publish workflow

---

cli/pack/common.go

Fixed the removal of temporary directory in prepareBundle function of pack module.
Follow up #18

Add missing removal of temporary directory

---

cli/cmd/init.go
cli/configure/configure.go
cli/create/internal/steps/load_manifest.go
cli/init/init.go
cli/init/init_test.go
cli/util/util.go
cli/util/util_test.go
test/integration/init/test_init.py

If tt config already exists, init command will ask for confirmation to overwrite it.

init: add check for tt env config existence

---

.github/actions/prepare-ce-test-env/action.yml
.github/actions/prepare-ee-test-env/action.yml
.github/actions/static-code-check/action.yml
.github/workflows/full-ci.yml
.github/workflows/tests.yml
magefile.go
test/integration/install/test_install.py
test/integration/pack/test_pack.py
test/pytest.ini

Setup-python and cache actions versions were updated to fix warnings about using deprecated functionality.
Closes #154

test: move long running tests to separate workflow

---

cli/cmd/create.go
cli/codegen/generate_code.go
cli/create/builtin_templates/builtin_templates.go
cli/create/builtin_templates/templates/cartridge/MANIFEST.yaml
cli/create/builtin_templates/templates/cartridge/app/admin.lua
cli/create/builtin_templates/templates/cartridge/app/roles/custom.lua
cli/create/builtin_templates/templates/cartridge/failover.yml
cli/create/builtin_templates/templates/cartridge/init.lua
cli/create/builtin_templates/templates/cartridge/instances.yml.tt.template
cli/create/builtin_templates/templates/cartridge/replicasets.yml
cli/create/builtin_templates/templates/cartridge/stateboard.init.lua
cli/create/builtin_templates/templates/cartridge/tt.post-build
cli/create/builtin_templates/templates/cartridge/tt.pre-build
cli/create/builtin_templates/templates/cartridge/{{.name}}-scm-1.rockspec.tt.template
cli/create/internal/steps/copy_app_template.go
cli/create/internal/steps/copy_app_template_test.go
cli/create/internal/steps/testdata/copy_template/templates/basic/echo.sh
doc/examples.rst
test/integration/create/test_create.py

First added built-in template is cartridge application template.
Closes #195

create: add support of built-in templates

---

doc/examples.rst

Add vshard bootstrap command as a final step for cartridge app creation example.

doc: update cartridge app creation example

---

test/integration/cartridge/test_cartridge.py

Added stop of instance after finish of the test, if instance is still running.
Also looked through other test to check for the same behavior.
Closes #128

test: fix cartridge test

---

test/integration/remove/test_remove.py

Removed check for run log message since it is now
outdated.
Follow up #210

test: remove outdated check

---

.github/workflows/macos.yaml
cli/cartridge/extra/003_fix_work_paths.patch
magefile.go

ci: add macos workflow

---

.github/workflows/full-ci.yml
CHANGELOG.md
cli/cmd/install.go
cli/docker/docker.go
cli/docker/docker_integration_test.go
cli/docker/testdata/Dockerfile
cli/install/Dockerfile.tnt.build
cli/install/install.go
go.mod
go.sum
test/integration/install/test_install.py

install: Tarantool build in docker

---

cli/cmd/clean.go
cli/cmd/daemon.go
cli/cmd/status.go
cli/process_utils/process_utils.go
cli/running/running.go

status: make instance status colorful

---

cli/pack/archive.go
cli/pack/archive_test.go
cli/pack/common.go
cli/pack/deb.go
cli/pack/opts.go
cli/pack/rpm.go
cli/util/git.go
test/integration/pack/test_bundles/bundle5/tarantool.yaml
test/integration/pack/test_pack.py

Fix find modules behavior in tt pack

---

cli/pack/common.go
test/integration/pack/test_pack.py

Close https://github.com/tarantool/tt/issues/238

Add rpm/deb integration tests

---

CHANGELOG.md
README.rst
cli/cmd/pack.go
cli/pack/archive.go
cli/pack/common.go
cli/pack/deb.go
cli/pack/docker.go
cli/pack/pack.go
cli/pack/rpm.go
cli/pack/templates/Dockerfile.pack.build
test/integration/pack/test_pack.py

Close https://github.com/tarantool/tt/issues/133

Add use-docker option

---

cli/pack/docker.go
test/integration/pack/test_pack.py

With this patch:
- Fixed integration tests
- Fixed generating a command of packing in container
Follow up #133

fix use-docker

---

cli/create/create.go
cli/create/internal/app_template/template_ctx.go
cli/create/internal/steps/cleanup.go
cli/create/internal/steps/collect_template_vars.go
cli/create/internal/steps/collect_template_vars_test.go
cli/install/install.go
cli/pack/docker.go
cli/templates/internal/engines/go_text_engine.go
cli/templates/internal/engines/go_text_engine_test.go
cli/templates/templates.go
cli/util/util.go

- use more restrictive interfaces in some functions in util package
- rename "engines" package to "templates"
- simplify reader code in create
- fix some staticcheck complaints in create module.

Minor code refactor

---

cli/running/running.go
cli/running/watchdog.go

With this patch a race condition between tt start and tt stop was fixed.
Close #264

Fix a race condition between tt start and tt stop

---

doc/examples.rst

doc: add tarantoolctl/cartridge to tt transition notes

---

cli/list/list.go

Added path to instanes in 'tt instances' output.
Old output: 
```
f.terekhin@f-terekhin tt221 % ./tt instances
List of enabled applications:
• 123             
• anime           
• app1            
router
master
replica
• test123        
```
New output:
```
f.terekhin@f-terekhin tt221 % ./tt instances                                     
List of enabled applications:
• 123 (/Users/f.terekhin/tt221/enables/123)
• anime (/Users/f.terekhin/tt221/enables/anime)
• app1 (/Users/f.terekhin/tt221/enables/app1)
router (router.init.lua)
master (init.lua)
replica (init.lua)
• test123 (/Users/f.terekhin/tt221/enables/test123.lua)
```

instances: add path to 'tt instances' output

---

CHANGELOG.md
cli/build/build.go
cli/build/build_test.go
cli/cmd/build.go
cli/cmd/create.go
cli/create/builtin_templates/templates/cartridge/MANIFEST.yaml
cli/create/internal/steps/create_temporary_app_dir.go
cli/create/internal/steps/enable_instance.go
cli/create/internal/steps/set_predefined_variables.go
cli/templates/internal/engines/go_text_engine.go
cli/templates/internal/engines/go_text_engine_test.go
cli/util/util.go
cli/util/util_test.go
test/integration/build/test_build.py
test/integration/create/test_create.py

- Fix typo in `create` help.
- Support building using application name.
- Fix symlink creation error when using custom application destination dir.

Fix app creation and build issues

---

cli/cmd/root.go

Warning messages are displayed in yellow, errors are in red.
Closes #392

tt: use color for warning/error log messages

---

CHANGELOG.md
cli/install/install.go
cli/install/install_test.go

install: add directory permissions check before building binaries

---

README.rst

doc: add installation section to README

---

README.rst

doc: install tt on gentoo linux

---

.github/workflows/publish.yml

Removed removal of CHANGELOG.md because it is not packed.
Follow up #367

cd: fix goreleaser

---

cli/init/init.go
cli/init/templates/tt.yaml.default

init: add comments to generating configuration

---

cli/rocks/rocks.go
test/integration/rocks/test_rocks.py

Add env var for cmake to find tarantool include dir.

rocks: fix rocks compilation

---

CHANGELOG.md
cli/cmd/search.go
cli/search/search.go
test/integration/search/test_search.py

search: add subcommands for tarantool/tarantool-ee/tt binaries

---

CHANGELOG.md
cli/install/install.go
cli/install/patch.go

Added openssl patch for tarantool 1.10.15.
Closes #464

install: add patch for tarantool 1.10.15

---

README.md

Add missing requirements.
Closes #508

readme: update test requirements

---

test/requirements.txt

Update pyyaml package version to fix deprecated option error.

test: fix pip error

---

cli/install/install.go
test/integration/install/test_install.py
test/integration/install/testdata/test_install_tt_already_exists/tt/tt.yaml

Removed duplicate log message: "Checking existing..."  from "tarantool-ee" installation.
Moved check for already existing version.
Removed TODO and added return of error since 'tt' now has releases.

install: refactor code

---

.github/workflows/publish.yml
.gitignore
CHANGELOG.md
cli/install/install.go
cli/util/util.go
test/integration/install/test_install.py

This is fast head-on solution, no code duplication removed.

Fix commit install failure

---

CHANGELOG.md
README.md
test/integration/init/apps/multi_inst_app/init.lua
test/integration/init/apps/multi_inst_app/instances.yml
test/integration/init/apps/multi_inst_app/router.init.lua
test/integration/instances/multi_app/app1/init.lua
test/integration/instances/multi_app/app1/instances.yml
test/integration/instances/multi_app/app1/router.init.lua
test/integration/restart/multi_app/app1/init.lua
test/integration/restart/multi_app/app1/instances.yml
test/integration/restart/multi_app/app1/router.init.lua
test/integration/restart/multi_app/instances_enabled/app1/init.lua
test/integration/restart/multi_app/instances_enabled/app1/instances.yml
test/integration/restart/multi_app/instances_enabled/app1/router.init.lua
test/integration/running/multi_app/app1/init.lua
test/integration/running/multi_app/app1/instances.yml
test/integration/running/multi_app/app1/router.init.lua
test/integration/running/multi_inst_app/init.lua
test/integration/running/multi_inst_app/instances.yml
test/integration/running/multi_inst_app/router.init.lua
test/integration/running/multi_inst_app_no_init/instances.enabled/mi_app/instances.yml
test/integration/running/multi_inst_app_no_init/instances.enabled/mi_app/router.init.lua
test/integration/running/multi_inst_app_no_init/instances.enabled/mi_app/storage.init.lua
tt.yaml.default

Remove trailing spaces all over the code.

tt: remove trailing spaces

---

.github/workflows/full-ci.yml
.github/workflows/tests.yml
.gitmodules
CHANGELOG.md
cli/rocks/extra/wrapper.lua
cli/rocks/rocks.go
cli/rocks/rocks_test.go
test/integration/rocks/test_rocks.py

Upgrade to the new luarocks-3.9.2 fork.
Closes #74

rocks: bump luarocks to 3.9.2

---

CHANGELOG.md

Move config format change line to Unreleased.

doc: fix changelog notes

---

CHANGELOG.md
cli/cmd/completion.go
cli/rocks/completions/bash_injection
cli/rocks/completions/bash_rocks
cli/rocks/completions/zsh_injection
cli/rocks/completions/zsh_rocks
cli/rocks/rocks.go
test/integration/completion/test_completion.py

added luarocks completions. The `tt rocks completion` and `tt rock admin completion` commands are disabled.
Closes #616 #44

completion: added luarocks completions

---

CHANGELOG.md
cli/cmd/cluster.go
test/integration/cluster/test_cluster.py
test/integration/cluster/testsimpleapp/config.yaml
test/integration/cluster/testsimpleapp/init.lua
test/integration/cluster/testsimpleapp/instances.yml

cluster: fix app:instance recognize as a etcd URL

---

test/integration/connect/test_connect.py

Scan queries without `SEQSCAN` keyword raise an error without `SEQSCAN` keyword since Tarantool 3.0 [1]. The keyword is supported since Tarantool 2.11.
1. https://www.tarantool.io/ru/doc/latest/reference/reference_sql/sql_statements_and_clauses/#from-clause

connect: fix integration tests with Tarantool 3.0

---

.github/workflows/full-ci.yml
.github/workflows/tests.yml
CHANGELOG.md
cli/create/builtin_templates/templates/cartridge/{{.name}}-scm-1.rockspec.tt.template

Make dependencies less strict to support newer rocks versions in local repositories.

create: less strict deps in cartridge template

---

test/integration/running/test_running.py

Fixed assertions in test_running.py

test: fixed assertions

---

CHANGELOG.md
README.md
cli/cmd/env.go
cli/cmd/root.go
cli/env/env.go
cli/env/env_test.go
test/integration/env/test_env.py

Added module that adds 'tt' and 'tarantool' (installed using 'tt') to the current environment.
Closes #338

tt: add env module

---

.github/actions/prepare-ce-test-env/action.yml

Run tests on tarantool 3.0 alpha3 to avoid a failure due to tarantool/tarantool#9275

test: run tests on tarantool 3.0.0~alpha3

---

CHANGELOG.md
cli/rocks/rocks.go
cli/rocks/rocks_test.go

Changed '--server' flag, so it now accepts several arguments.
Closes #686

rocks: '--server' flag now accepts several arguments

---

cli/install_ee/install_ee.go

Added close of response if status code is not OK.
Found by Svacer.

install: close response if status code is not OK

---

cli/running/watchdog.go

This patch properly finalises goroutines performing integrity checks. This prevents hanging of watchdog upon stopping the instance with integrity checks turned on.

watchdog: properly finish goroutine for periodic integrity checks

---

README.md

Add information about configuring venv and dependencies installation.

doc: supplement tests execution steps description

---

.github/actions/setup-etcd/action.yml
.github/workflows/full-ci.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
ci/Dockerfile
cli/create/internal/steps/move_app_dir_test.go
cli/docker/docker_integration_test.go
cli/install/install_test.go
cli/running/running_test.go
cli/util/util_test.go
goreleaser/.goreleaser_linux_arm64.yml
magefile.go
magefile.publish.go
test/integration/init/test_init.py
test/integration/install/test_install.py
test/integration/pack/test_pack.py
test/pytest.ini

ci: build and release for aarch64

---

CHANGELOG.md
cli/cmd/kill.go
cli/cmd/root.go
cli/process_utils/process_utils.go
cli/running/cluster_instance.go
cli/running/instance.go
cli/running/process_controller.go
cli/running/running.go
cli/running/script_instance.go
cli/running/watchdog.go
test/integration/running/test_running.py
test/requirements.txt
test/utils.py

``tt kill`` allows to kill instance(s) with SIGKILL and SIGQUIT signals.
Closes #585

Added ``tt kill`` module

---

CHANGELOG.md
cli/cmd/create.go
cli/cmd/create_test.go
cli/codegen/generate_code.go
cli/create/builtin_templates/builtin_templates.go
cli/create/builtin_templates/templates/single_instance/MANIFEST.yaml
cli/create/builtin_templates/templates/single_instance/config.yml
cli/create/builtin_templates/templates/single_instance/init.lua.tt.template
cli/create/builtin_templates/templates/single_instance/instances.yml

Title: `tt create`: a new template single_instance
The template creates a single instance application for Tarantool 3.

create: add simple application template

---

CHANGELOG.md
cli/running/script_instance.go
cli/running/script_instance_test.go

start: fix socket path overflow check

---

CHANGELOG.md
cli/cmd/status.go
cli/status/status.go
test/integration/running/test_running.py
test/utils.py

`tt status` now displays the mode of the instance.
Closes #835

status: show RO/RW status

---

CHANGELOG.md
README.md
cli/cmd/root.go
cli/configure/configure.go
cli/configure/configure_test.go
test/integration/cli/test_launch.py

Added 'TT_CLI_CFG' environmental variable to specify the path to configuration file.
Closes #813

tt: add 'TT_CLI_CFG' environmental variable

---

CHANGELOG.md
cli/cfg/dump_test.go
cli/configure/configure.go
test/integration/instances/test_instances.py

start: fix incorrect application name

---

.github/workflows/publish.yml

Use the exact version of the 'goreleaser' package.

cd: fix mac os publish workflow

---

CHANGELOG.md
cli/rocks/rocks.go
test/integration/rocks/test_rocks.py

Updated `tarantool/luarocks` dependencie to `v3.10.0`.
Closes #811

rocks: bump luarocks 

---

cli/install/install.go

Since it was not entirely clear where tarantool/tt was installed, messages were added indicating the installation path of binary and symbolic link.
Closes https://github.com/tarantool/tt/issues/483

install: added message with installation path

---

cli/cmd/clean.go
test/integration/running/test_running.py

The tt clean output where cumbersome, so it was made more compact. Now, without the tt -V flag, the output will be compact and clear.
Closes [875](https://github.com/tarantool/tt/issues/875)

clean: make output more compact

---

README.md

etcd and lua have been added to the dependencies list

doc: add etcd to test dependencies

---

cli/cmd/cluster.go

There were a little mistake in removeRolesCmd Flags

cluster: remove roles flags fix

---

cli/cmd/log.go
cli/tail/tail.go
cli/tail/tail_test.go
test/integration/log/test_log.py

Fix double closing the chanel on log dirs removing.

log: fix crash on removing log dir

---

CHANGELOG.md
cli/cfg/dump_test.go
cli/config/config.go
cli/configure/configure.go
cli/configure/configure_test.go
cli/configure/testdata/modules_cfg/tt-modules1.yaml
cli/configure/testdata/modules_cfg/tt-modules2.yml
cli/configure/testdata/modules_cfg/tt-modules3.yaml
cli/configure/testdata/modules_cfg/tt-modules4.yml
cli/configure/testdata/modules_cfg/tt-modules5.yaml
cli/init/init.go
cli/init/init_test.go
cli/init/templates/tt.yaml.default
cli/modules/modules.go
cli/pack/common.go
cli/pack/common_test.go
cli/util/util.go
test/integration/cfg/test_dump.py
test/integration/init/test_init.py

Revert "modules: tt.yaml modules/directory support list"

---

CHANGELOG.md
cli/coredump/scripts/gdb.sh

coredump: fix inspect failure for tarantool-ee coredumps

---

cli/aeon/cmd/connect.go
cli/aeon/cmd/transport.go
cli/aeon/cmd/transport_test.go
cli/cmd/aeon.go
cli/cmd/root.go
test/integration/aeon/test_aeon.py
test/integration/aeon/testdata/ca.key
test/integration/aeon/testdata/certfile.key
test/integration/aeon/testdata/private.key

aeon: connect dummy implementation

---

CHANGELOG.md

- Added changes introduced with #979
- Added changes introduced with #1006

Сhangelog fixup

---

.github/actions/static-code-check/action.yml
cli/config/single_or_array_test.go

test: fix loopclosure problem detected by golangci-lint-v1.63

---

CHANGELOG.md
cli/cmd/connect.go
cli/cmd/replicaset.go
test/integration/replicaset/test_replicaset_downgrade.py

Closes #1073
@TarantoolBot
title: replicaset downgrade: make version a positional argument

replicaset downgrade: make version a positional argument

---

CHANGELOG.md
cli/formatter/format_test.go
cli/formatter/table.go

formatter: fix rendering of empty maps

---

CHANGELOG.md
cli/cmd/root.go
cli/cmd/tcm.go

Title: add the TCM command
Added the tt tcm start command
Usage: tt tcm start
Closes: TNTP-1771

tcm: add the TCM command

---

CHANGELOG.md
cli/cluster/cluster.go
cli/cluster/cmd/common.go
cli/cluster/cmd/uri.go
cli/cluster/cmd/uri_test.go
golangci-lint.yml
lib/dial/dial.go
lib/dial/dial_test.go
lib/dial/opts.go
lib/dial/ssl.go
lib/dial/ssl_disable.go
lib/dial/transport.go
lib/dial/transport_test.go
magefile.go

tls: build without openssl linkage

---

CHANGELOG.md
cli/cluster/cmd/common.go
cli/cluster/cmd/failover.go
cli/cluster/cmd/publish.go
cli/cluster/cmd/replicaset.go
cli/cluster/cmd/show.go
cli/cluster/cmd/uri.go
cli/cluster/cmd/uri_test.go
cli/cmd/cluster.go
cli/cmd/connect.go
cli/cmd/replicaset.go
go.mod
lib/connect/help.go
lib/connect/help_test.go
lib/connect/uri.go
lib/connect/uri_test.go

cluster: moved cmd.UriOpts to connect

---

CHANGELOG.md

The release includes minor fixes identified by Svacer and CVE linters.

Release 2.9.1

---

.github/actions/prepare-ce-test-env/action.yml
.github/actions/prepare-ee-test-env/action.yml
.github/workflows/publish.yml
CHANGELOG.md
cli/cmd/completion.go
cli/rocks/completions/fish_injection
cli/rocks/completions/fish_rocks
goreleaser/.goreleaser_linux.yml
goreleaser/.goreleaser_linux_arm64.yml
test/integration/completion/__init__.py
test/integration/completion/conftest.py
test/integration/completion/helpers/bash_completion.sh
test/integration/completion/helpers/fish_completion.sh
test/integration/completion/test_completion.py

Added support for autocomplete for `fish` shell and add integration test on completion.
@TarantoolBot
Title: add completion support for `fish` shell.
Added support for autocomplete when working interactively in the console
for the `fish` shell. Use `tab` to display hints of available
command entry sequence.
**Usage Example**:
```fish
eval "$(tt completion fish)"
```
Closes #TNTP-2893

completion: add fish completion support
