cli/running/running.go

Previously if no application name was specified output was:
"Currently, you can specify only one instance at a time."
which is incorrect. So I processed it.

Add processing of error when no application name is specified

---

cli/running/instance.go
cli/running/lua/launcher.lua

Previously instance launch code was passed to tarantool
using "-e" flag, so it showed code in ps.
To solve it i passed code through stdin pipe using
"-" flag.

ps ax|grep tarantool showes lua code

---

cli/running/instance.go
cli/running/lua/launcher.lua

This patch enables linebuffering for stdout fstream.
Closes #36

launcher: fix stdout buffering

---

go.mod
go.sum

All of our patches have been accepted upstream.
Accordingly, it no longer makes sense to use our fork.

build: switch gopher-lua to upstream repo

---

test/integration/rocks/test_rocks.py

By default `rocks doc` will open documentation in browser.
We do not need this in tests.

test: rocks doc should list documentation files

---

test/integration/running/test_running.py
test/utils.py

Before the patch, a race may occur in the "logrotate" test, when the log files are checked on existen in the directory but they have not yet been created.

Fix logrotate test

---

cli/cmdcontext/cmdcontext.go
cli/modules/config.go
cli/running/instance.go
cli/running/instance_test.go
cli/running/lua/launcher.lua
cli/running/running.go
cli/running/watchdog_test.go

If tarantool version is above 2.8.1 we use env variables to set wal, vinyl and memtx dirs, else we use cfg.wrapper to do it.
It allows to set memtx_dir vinyl_dir and wal_dir. if they are blank it creates datadirs in the app_path (instance_name_datadir).
Resolve #30

Implement box.cfg() wrapper

---

README.rst

The `available` parameter is actually called `instances_available`.

readme: fix instances_available parameter

---

cli/cmd/connect.go
cli/cmdcontext/cmdcontext.go
cli/connect/connect.go

This patch changes the behavior of `connect` so that the source for the code evaluation is now passed by using the `-f` flag.
Part of #58

Add `-f` flag for evaluation

---

cli/crud/lua/import.lua

A change in the crud api has been taken into account, now in the error variable from batching operation the key with tuple value has actual name (`tuple` -> `operation_data`).
Related with [this](https://github.com/tarantool/tt/pull/75#discussion_r906307118).
Part of #87

Update logic of crud batching api

---

cli/cmd/run.go

Moved description of '--' flag to long definition of tt run.
Follow up #29

run: move descriptions to long definition

---

.github/workflows/tests.yml

Solution is taken from:
golangci/golangci-lint-action#119 (comment)

ci: fix no line numbers shown for golangci

---

cli/cmdcontext/cmdcontext.go
cli/rocks/extra/hardcoded.lua
cli/rocks/rocks.go
cli/util/util.go
test/integration/rocks/files/testapp-scm-1.rockspec
test/integration/rocks/test_rocks.py

When the spec file contains a tarantool dependency, luarocks
checks the tarantool version against the _TARANTOOL global variable.
Since luarocks ran inside the tarantool in tarantoolctl, there were
no problems with this. Luarocks launched from tt
is served by gopher-lua and has no direct access to tarantool variables,
accordingly, a new way of checking dependencies was added, namely:
Added variables TT_CLI_TARANTOOL_PATH and TT_CLI_TARANTOOL_VERSION.
This will allow luarocks to correctly add tarantool to the list of
dependencies and run the correct version of tarantool for internal needs.
Also in this patch are outlines for solving the problem with the correct
determination of the path to the directory with the header files of the
tarantool.
`tt rocks make` test was added.
Also, to solve …

rocks: fix make command

---

cli/cmd/cat.go
cli/cmd/check.go
cli/cmd/completion.go
cli/cmd/connect.go
cli/cmd/coredump.go
cli/cmd/logrotate.go
cli/cmd/play.go
cli/cmd/restart.go
cli/cmd/start.go
cli/cmd/status.go
cli/cmd/stop.go

Refactoring of cli language that describe usage of tt commands.
Now a single notation is used to specify positional arguments through brackets `<>`, and 3 points `...` is also used to indicate the possibility of transmitting multiple parameters.
Fixed inaccuracies in the description of some parameters that must be not optional, but required.
Close #63

tt: cli language refactoring

---

.github/workflows/tests.yml
README.rst
cli/cartridge/extra/003_fix_work_paths.patch
cli/cartridge/extra/004_fix_warning.patch
cli/cmd/check.go
cli/cmd/clean.go
cli/cmd/connect.go
cli/cmd/logrotate.go
cli/cmd/restart.go
cli/cmd/root.go
cli/cmd/start.go
cli/cmd/status.go
cli/cmd/stop.go
cli/cmdcontext/cmdcontext.go
cli/configure/configure.go
cli/running/instance.go
cli/running/instance_test.go
cli/running/lua/launcher.lua
cli/running/running.go
cli/running/watchdog_test.go
cli/util/util.go
doc/examples.rst
magefile.go
test/integration/cartridge/test_cartridge.py
test/integration/running/test_running.py
test/utils.py

This patch adds the ability to works with a set of instances.
For example, we want to launch two instances based on one init.lua
file and one connected instance based on the router.lua file.
In order to do this, we create a directory called demo with the content:
init.lua:
local inst_name = os.getenv('TARANTOOL_INSTANCE_NAME')
local app_name = os.getenv('TARANTOOL_APP_NAME')
while true do
if app_name ~= nil and inst_name ~= nil then
print(app_name .. ":" .. inst_name)
else
print("unknown instance")
end
require("fiber").sleep(1)
end
router.init.lua:
local inst_name = os.getenv('TARANTOOL_INSTANCE_NAME')
local app_name = os.getenv('TARANTOOL_APP_NAME')
while true do
print("custom init file...")
if app_name ~= nil and inst_name ~= nil then
print(app_name .. ":" .. inst_name)
else …

tt: working with a set of instances

---

test/integration/rocks/test_rocks.py

Without this patch a user catches an error when calling mage test:
```
test/integration/rocks/test_rocks.py:32:11: E275 missing whitespace after keyword
test/integration/rocks/test_rocks.py:46:11: E275 missing whitespace after keyword
test/integration/rocks/test_rocks.py:53:11: E275 missing whitespace after keyword
Error: running "python3 -m flake8 test" failed with exit code 1
```
In CI this linter rule is ignored.
Flake8 version: `4.0.1`
Follow up #14

lint: fix linter errors in rocks tests

---

cli/create/internal/steps/run_hook.go
cli/create/internal/steps/run_hook_test.go

Missing hooks currently gives an error: "permission denied", when trying to execute an application directory :)
Need to skip hook execution if it is not present in template manifest.
Unit test is added.

create: fix missing hooks exec error

---

cli/create/internal/steps/render_template.go
cli/create/internal/steps/render_template_test.go
cli/create/internal/steps/testdata/cartridge/{{.user_name}}.cfg.tt.template

If a file name is in <name>.tt.template format, it is renamed to the <name>. The issue is: if <name> also contains template variables like {{.var}} the instantiation engine tries to instantiate old file name (<name>.tt.template) and rename it. But this file does not exists after first renaming. So there is "no such file or directory error". The fix is to update file name after the first renaming.
Covered by unit test.

create: fix template file name rendering

---

cli/cmd/connect.go
cli/cmd/connect_test.go
test/integration/connect/test_connect.py
test/integration/connect/test_localhost_app/test_app.lua
test/integration/connect/test_multi_app/init.lua
test/integration/connect/test_multi_app/instances.yml
test/integration/connect/test_multi_app/router.init.lua
test/integration/connect/test_single_app/test_app.lua

The patch fixes connection to a Tarantool instance via URI. The issue was introduced with a pull request to work with a set of intances [1]. The rules for determining the URI are similar to used by a connector [2].
1. https://github.com/tarantool/tt/pull/113
2. https://github.com/tarantool/tt/blob/da319ff9a1d0d7bd12e6f682d6ef906c965dbfa5/cli/connector/conn_opts.go#L47-L69
Closes #138
I was looking at the connector code to determine is a string a URI. But I want to suggest making rules to detect valid URI for `tt connect` more strict:
1. Left only `tcp://host:numeric_port` or `host:numeric_port` for tcp-socket connections.
2. Left only `unix://path/to/file` for unix-socket connections.
From my point of view it will simplify both our and users lives.

connect: fix connect via URI

---

cli/create/create.go
cli/create/internal/steps/load_vars_file.go
cli/create/internal/steps/load_vars_file_test.go
cli/create/internal/steps/set_predefined_variables.go
cli/create/internal/steps/set_predefined_variables_test.go
test/integration/create/templates/basic/MANIFEST.yaml
test/integration/create/test_create.py

It is convenient to have some template variables with pre-defined values. "name" var is added. Its value is an application name passed using --name flag.

create: add pre-defined variables

---

.github/workflows/tests.yml
cli/cmd/connect.go
cli/cmdcontext/cmdcontext.go
cli/connect/connect.go
cli/connect/console.go
cli/connect/language.go
cli/connect/language_test.go
test/integration/connect/test_connect.py
test/integration/connect/test_file/hello.lua
test/integration/connect/test_file/hello.sql

The `-l` or `--language` flag allows a user to switch default
language for a connection. A value can be `lua` or `sql`.
Part of https://github.com/tarantool/tt/issues/58
The patchset also replaces Tarantool 2.8 to 2.10 on CI as a last release version.

connect: add language flag

---

cli/install_ee/install_ee.go
cli/version/version_tools.go

The tarantool-ee tarballs for Linux have nogc64 versions. We must support them.

search: support nogc64 tarbolls

---

README.rst
cli/config/config.go

This patch fixes `repo` description in Readme and config.go.

cfg: repo description fixes

---

cli/configure/configure.go
cli/configure/configure_test.go
cli/util/util.go
cli/util/util_test.go
test/integration/cli/test_launch.py
test/integration/install/test_install.py

Be default tt changes working directory to tarantool.yaml location. This causes a lot of issues with using relative paths in tt code. Changing working directory is removed.

create: remove working directory change

---

cli/cmd/install.go
cli/cmd/remove.go
cli/install/install.go
cli/remove/remove.go
cli/search/search.go

Old format `program`=`version` resulted in escaping with quotes when working with a file from a shell.
New format is `program`_`version`.

install: file name format changed

---

cli/cmd/root.go
cli/cmdcontext/cmdcontext.go
cli/configure/configure.go
cli/configure/configure_test.go
cli/configure/testdata/bin_dir/tarantool
cli/configure/testdata/bin_dir/tt
test/integration/cli/test_launch.py
test/integration/remove/test_remove.py

- Verbose mode support is added. Use -V to see debug log output.
- Only one of -S, -L, --cfg options can be specified.
- If tarantool executable is missing in bin_dir, a default from /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/psergee/go/bin:/home/psergee/work/tarantool/build/extra/dist/
will be used if available.
- If tt executable is missing in bin_dir, current process is used.
- System config is not loaded if -L of --cfg options are specified and
local config is missing.
Closes #174

tt: re-work executables search logic

---

.codespellrc
cli/install/extra/bump-libunwind-new.patch
cli/install/extra/bump-libunwind-old.patch
cli/install/extra/bump-libunwind.patch
cli/install/extra/gh-6686-fix-build-with-glibc-2-34.patch
cli/install/extra/openssl-symbols-1.10.14.patch
cli/install/extra/openssl-symbols.patch
cli/install/extra/tarantool-static-build.patch
cli/install/extra/zlib-backup-old.patch
cli/install/extra/zlib-backup.patch
cli/install/install.go
cli/install/patch.go
cli/install/patch_test.go
cli/search/search.go
cli/util/util.go

Backported static build system for versions 1.10.
For the successful assembly of older versions,
additional patches have been applied:
* openssl-symbols.patch - Fix missing OpenSSL symbols.
* gh-6686-fix-build-with-glibc-2-34.patch - Necessary
for building with >= glibc-2.34.
* zlib-backup.patch - zlib version 1.2.11 is no longer
available for download.
* bump-libunwind.patch - Old version of the libunwind
doesn't compile under GCC > 10.
Closes #175

install: fix static build

---

test/integration/play/test_file/remote_instance_cfg.lua
test/integration/play/test_play.py
test/utils.lua
test/utils.py

Added free port auto resolve mechanism for integration tests, which require the running of a tarantool instance:
The idea is using a `box.cfg({listen = '127.0.0.1:0'})` call in the test instance configuration file and get an automatically assigned port with [box.info.listen](https://github.com/tarantool/tarantool/commit/1f4b9afb9db740aeeba71d7667ce13905597430d). For tarantool v1 we use [snippet](https://github.com/tarantool/tt/pull/112#issuecomment-1209661575) below for getting assigned port with `SO_REUSEADDR` socket filter by [this](https://github.com/tarantool/tt/pull/112#issuecomment-1232949223) approach. 
Now the solution looks like this:
If the user needs to raise a test instance for integration tests, then the user writes the configuration file of the test instance (for example, …

test: add free port auto resolve mechanism

---

cli/configure/configure_test.go

Some unit tests rely on missing tt configs in parent directories.
To make sure developer config does not affect these unit tests, make
chdir to temporary directory for these tests.

tt: run unit test in tmp dir

---

.github/workflows/tests.yml
.isort.cfg
README.rst
cli/build/build.go
cli/connect/console.go
cli/connector/connector.go
cli/connector/eval_plain_text.go
cli/connector/protocol_test.go
cli/install/install.go
cli/running/running.go
cli/running/watchdog.go
golangci-lint.yml
test/integration/cartridge/test_cartridge.py
test/integration/cli/test_launch.py
test/integration/connect/test_connect.py
test/integration/help/test_help.py
test/integration/pack/test_pack.py
test/integration/play/test_play.py
test/integration/remove/test_remove.py
test/integration/running/test_running.py

Flake8 tests were forgotten when implementing golangci-lint.

ci: run flake8 linter separately

---

go.mod
go.sum

The patch replaces a commit version of go-tarantool with the latest release version.

connector: bump go-tarantool version to 1.9.0

---

.github/workflows/tests.yml
.lichen.yaml
README.rst
magefile.go

We need to check the licenses of modules that came from dependencies. CI should return an error if the licenses are not in the list:
BSD-2
MIT
Apache-2.0
BSD
MPL-2.0
Close #205

ci: add license checker

---

go.mod
go.sum

Vulnerable versions: < 1.5.13
Impact:
A bug was found in containerd's CRI implementation where programs inside a container can cause the containerd daemon to consume memory without bound during invocation of the ExecSync API. This can cause containerd to consume all available memory on the computer, denying service to other legitimate workloads. Kubernetes and crictl can both be configured to use containerd's CRI implementation; ExecSync may be used when running probes or when executing processes via an "exec" facility.
CVE ID: CVE-2022-31030
GHSA ID: GHSA-5ffw-gxpp-mxpf

Update containerd version to 1.5.13

---

CHANGELOG.md
README.rst
cli/cmd/daemon.go
cli/cmd/root.go
cli/cmd/start.go
cli/cmdcontext/cmdcontext.go
cli/config/daemon_cfg.go
cli/configure/configure.go
cli/daemon/api/http.go
cli/daemon/api/parser.go
cli/daemon/daemon.go
cli/daemon/httpserver.go
cli/daemon/process.go
cli/daemon/process_test.go
cli/daemon/process_test_helpers.go
cli/daemon/test_process/test_process.go
cli/process_utils/process_utils.go
cli/running/running.go
doc/examples.rst
go.mod
go.sum
test/integration/daemon/test_app/test_app.lua
test/integration/daemon/test_daemon.py
test/requirements.txt
test/utils.py

`tt daemon` module is used to manage HTTP server
running on the background. HTTP server can process
`tt` commands such as `start`, `status`, etc.
Daemon can be configurated with `tt_daemon.yaml` config.
`tt_daemon.yaml` file format:
```yaml
daemon:
run_dir: path
log_dir: path
log_maxsize: num (MB)
log_maxage: num (Days)
log_maxbackups: num
log_file: string (file name)
listen_interface: string
port: num
pidfile: string (file name)
```
The following set of commands is implemented:
* `tt daemon start` - launch of a daemon;
* `tt daemon stop` - terminate of the daemon;
* `tt daemon status` - get daemon status;
* `tt daemon restart` - daemon restart.
Closes #10

tt: daemon module

---

.github/workflows/full-ci.yml
.github/workflows/tests.yml

Such pull requests may be labeled with `ee-ci` or `full-ci` to run tests with Tarantool EE. To avoid security problems, the label must be reset manually for every run.

ci: fix EE tests for outside pull requests

---

cli/pack/rpm_header.go

With this patch the architecture of an rpm package get defined by mapping the current architecture of the host system defined in runtime.GOARCH constant to rpm architecture valid values.
Follow up #18
Follow up #149

Fix rpm architectures values in tt pack

---

README.rst
cli/daemon/process_test.go
cli/daemon/process_test_helpers.go
go.mod
go.sum

Unit test failed for systemd because of check if
process is daemonized. Daemonization was checked
with PPID == 1. But PPID == 1 is no guarantee
that it is a daemon, for systemd daemon PPID is
systemd unit that managing daemon process.
But if proceess is detached from it's controlling
terminal, it is a daemon. But it is difficult to
check by means of Golang. This commit removes
daemonization check.
Closes #230

daemon: fix unit test

---

.lichen.yaml
CHANGELOG.md
cli/connector/connector.go
cli/running/instance.go
cli/running/instance_test.go
cli/running/lua/launcher.lua
go.mod
go.sum
test/integration/cartridge/test_cartridge.py

Now relative path is used instead of real for console socket.
It is used to prevent console socket path from being too long.
Closes #124

launcher: add fix for long socket paths

---

.github/workflows/full-ci.yml
.github/workflows/tests.yml

It is required to set `ref` and `repository` param for checkout in case of `pull_request_target` because the target runs in the context of the base commit.

ci: fix checkout with pull_request_target

---

cli/install/install.go
cli/version/version_tools.go
cli/version/version_tools_test.go

The tag format in tt will be changed from X.Y.Z to vX.Y.Z. The old format also needs to be supported. For example:
`tt install tt=0.2.0` should install v0.2.0 if such a version exists.

install: support new tag format

---

cli/running/lua/launcher.lua

If an incorrect lua code is run, the user will not see an error. For example:
$ cat a.lua
print("test"
$ tarantool a.lua
LuajitError: a.lua:2: ')' expected (to close '(' at line 1) near '<eof>' fatal error, exiting the event loop
$ tt run a.lua
Failed to run instance: a.lua
⨯ exit status 1
After applying this patch:
$ tt run a.lua
Failed to run instance: a.lua, error: "a.lua:2: ')' expected (to close '(' at line 1) near '<eof>'"
⨯ exit status 1

tt: log luajit errors

---

.gen_tarballs.sh

Tarballs helper script was fixed for working
with a new tag format (vX.Y.Z).

tt: fix tarballs helper

---

cli/install_ee/install_ee.go

Here is how it looks after the fix:
```
$ ./tt search tarantool-ee
• Available versions of tarantool-ee:
Enter username: 
Enter password: 
⨯ HTTP request error: Unauthorized
```
Part of #246

search: print http error description

---

CHANGELOG.md
cli/build/local.go
cli/cmd/cartridge.go
cli/cmd/restart.go
cli/create/internal/steps/move_app_dir.go
test/integration/cartridge/test_cartridge.py
test/integration/restart/test_app.lua
test/integration/restart/test_restart.py
test/integration/running/test_running.py

- Added `tt restart` confirmation prompt. `-y` option is added to accept restart without prompting.
- `tt cartridge` sub-commands `create`, `build`, `pack` are removed. Some message from cartridge were added to `tt build` and `tt create`
Part of #246

Minor changes for cartridge and restart

---

test/integration/restart/test_restart.py

PID check cannot be used to test if restart is completed due to race condition between start and restart commands: #264 
Checks for PID changes are removed.

restart: fix flaky restart integration test

---

cli/cmd/run.go
cli/codegen/generate_code.go
cli/running/instance.go
cli/running/lua/launcher.lua
test/integration/run/test_run.py

* `tt run` uses exec instead of child Tarantool process.This change fixes some issues like:
```
echo 'print(42)' | ../../tt/tt run -
⨯ specify script : 
```
and
```
echo 'print(...) print(unpack(arg))' | ../../tt/tt run -- - a b c
⨯ specify script : -
```
* `tt run` help is updated.

run: minor fixes in tt run

---

.goreleaser.yml

configure.defaultConfigPath was not set for goreleaser build.

cd: add missing build flag

---

cli/cmd/completion.go
cli/cmd/install.go
cli/cmd/search.go
cli/cmd/uninstall.go
cli/uninstall/uninstall.go
cli/uninstall/uninstall_test.go

Enable keyword completion for:
tt search (static)
tt install (static)
tt uninstall (runtime)
Example:
$ tt uninstall tarantool=
tarantool=2.10.2  tarantool=2.10.3  tarantool=2.8.4   tarantool=master
$ tt search t
tarantool     tarantool-ee  tt

completion: search, install and uninstall keywords

---

tarantool.yaml.default

Now we use absolute path instead of relative.

tt: distfiles path changed in default config

---

tarantool.yaml.default

Now we use absolute path instead of relative.

tt: change bin_dir and inc_dir path in default cfg

---

README.rst
magefile.go
test/integration/search/test_search.py

- Update readme testing info.
- Add new mage command to run full test.
- Mark one of search tests as slow. `mage integration`: 01:51 - before, 49.15s - after.

Minor changes in docs and tests

---

cli/cmd/build.go
cli/cmd/cat.go
cli/cmd/check.go
cli/cmd/clean.go
cli/cmd/common.go
cli/cmd/completion.go
cli/cmd/connect.go
cli/cmd/coredump.go
cli/cmd/create.go
cli/cmd/daemon.go
cli/cmd/init.go
cli/cmd/install.go
cli/cmd/logrotate.go
cli/cmd/pack.go
cli/cmd/play.go
cli/cmd/restart.go
cli/cmd/rocks.go
cli/cmd/run.go
cli/cmd/search.go
cli/cmd/start.go
cli/cmd/status.go
cli/cmd/stop.go
cli/cmd/uninstall.go
cli/cmd/version.go
cli/connect/connect.go
cli/running/running.go
cli/util/util.go
test/integration/search/test_search.py

Added new error type ArgError. returning this
error from command implementation causes
printing command usage help.
Closes #246

tt: print usage for arg errors for some commands

---

doc/examples.rst

Before this PR directory tree was displayed
incorrect in `Packing environments` section:

doc: fix packing environments section

---

CHANGELOG.md
README.rst
cli/cfg/dump.go
cli/cfg/dump_test.go
cli/cfg/testdata/tt_cfg.yaml
cli/cmd/cfg.go
cli/cmd/cfg_dump.go
cli/cmd/root.go
cli/configure/configure.go
cli/configure/configure_test.go
cli/util/util.go
cli/util/util_test.go
test/integration/cfg/test_dump.py
test/integration/cfg/tt_cfg.yaml

tt: implement cfg dump module

---

cli/create/internal/steps/enable_instance.go

If force mode is enabled, tt create must replace existing application symlink in instances enabled. No warning message in force mode if application symlink already exists.

create: replace app symlink in force mode

---

cli/cmd/root.go
cli/install/install.go
test/integration/cli/test_launch.py

Error, warning and fatal log messages will be written to stderr stream. Other messages will be written to stdout.
The test from the issue:
```
$ tt status app1 2>/dev/null
• app1:s1-replica: RUNNING. PID: 36692.
• app1:s2-master: RUNNING. PID: 36693.
• app1:s2-replica: RUNNING. PID: 36694.
• app1:stateboard: RUNNING. PID: 36695.
• app1:router: RUNNING. PID: 36696.
• app1:s1-master: RUNNING. PID: 36704.
```
Closes #157

tt: stdout/stderr for different log levels

---

CHANGELOG.md
README.rst
cli/running/lua/launcher.lua
test/integration/running/test_env_app/test_env_app.lua
test/integration/running/test_running.py

Starting from version 2.8.1, we can specify configuration parameters via special environment variables. Added support of all of them for the old tarantool.
Close #142

launcher: add support of all config variables

---

CHANGELOG.md
cli/cartridge/extra/001_make_cmd_public.patch
cli/create/internal/steps/move_app_dir_test.go
go.mod
go.sum

The new version of cartridge cli fixes several vulnerabilities in dependencies.

cartridge: bump 2.12.4 version

---

CHANGELOG.md
cli/cmd/create.go
cli/create/builtin_templates/templates/cartridge/MANIFEST.yaml
cli/create/context/create_ctx.go
cli/create/create.go
cli/create/internal/app_template/manifest.go
cli/create/internal/steps/print_follow_up_msg.go
cli/create/internal/steps/print_follow_up_msg_test.go
cli/create/internal/steps/set_predefined_variables.go
cli/templates/internal/engines/go_text_engine.go
cli/templates/internal/engines/go_text_engine_test.go
test/integration/create/test_create.py

Added support of follow-up messages to make it simpler to start to work with recently created app.
```
$ ../tt create cartridge --name app1 -f
• Creating application in /tmp/test/app1
• Using built-in 'cartridge' template.
• Application 'app1' created successfully
What's next?
Build and start 'app1' application:
$ tt build app1
$ tt start app1
To bootstrap vshard run the following command:
$ tt cartridge replicasets setup --bootstrap-vshard --name app1 --run-dir var/run/app1
```

Add app template follow up message

---

golangci-lint.yml
magefile.go

mage lint and mage unit fails without pkg-config tool. This tool is required to build go-openssl. tt is built with disabled ssl, so it must be disabled for lint and unit tests also.

tt: disable ssl for lint and unit builds

---

cli/running/running.go

Added check if tarantool executable is present in system
Old behavior:
```
hppro:~/work/tmp/env$ tarantool
Command 'tarantool' not found, but can be installed with:
sudo snap install tarantool  # version 1.9~git, or
sudo apt  install tarantool  # version 2.6.0-1ubuntu3
See 'snap info tarantool' for additional versions.
hppro:~/work/tmp/env$ ../../tt/tt start app1:router
• Starting an instance [router]...
hppro:~/work/tmp/env$ cat var/log/app1/router/router.log 
2022/11/08 21:00:47 Watchdog(ERROR): "exec: "": executable file not found in $PATH".
```
New behavior:
```
f.terekhin@f-terekhin tt221 % tarantool
zsh: command not found: tarantool
f.terekhin@f-terekhin tt221 % ./tt start test_app
⨯ tarantool binary not found
```
Closes #218

running: add check for tarantool executable

---

.github/actions/prepare-ce-test-env/action.yml

Current 1.10 tarantool package does not start systemd service after installation. So stopping is not required.

ci: remove stopping 1.10 service

---

cli/running/running.go
cli/running/watchdog.go
cli/running/watchdog_test.go

This patch fixes the problem, which was occurring when the watchdog
process received a signal SIGURG from go runtime[1][2] and passed it
to the forked process before the exec call. Fixed by adding a call of
the Ignore function. Receiving this signal is unexpected, cause tt
doesn't work with sockets at all.
Also this patch fixes the signals handling strategy. Now there is only
one handling loop for all signals. Added two fields for controlling
a state of the instance being watched and a mutex for synchronizing
the goroutines changing them.
[1] - https://go.googlesource.com/proposal/+/master/design/24543-non-cooperative-preemption.md
[2] - https://github.com/golang/go/issues/37942
Closes https://github.com/tarantool/tt/issues/325

Ignore SIGURG at Start command

---

cli/pack/systemd_dir.go
cli/pack/systemd_dir_test.go
cli/pack/templates/app-inst-unit-template.txt
cli/pack/templates/app-unit-template.txt
cli/pack/testdata/expected-unit-content-1.txt
cli/pack/testdata/expected-unit-content-2.txt
cli/pack/testdata/expected-unit-content-3.txt
cli/pack/testdata/fully-defined-params.yaml
test/integration/pack/test_pack.py

With this patch:
- added tests for checking that systemd units are visible for systemd after installation.
- replaced the path to tt.yaml in ExecStart script with the path to the directory where this file is located. It is needed to use tt with -L option.
- added a stop script section to systemd unit file by packing
Closes #330 
Closes #332

Fix systemd units generation in pack

---

CHANGELOG.md
README.rst
cli/cfg/dump_test.go
cli/config/config.go
cli/configure/configure.go
cli/running/path_builder.go
cli/running/path_builder_test.go
cli/running/running.go
test/integration/running/test_running.py
tt.yaml.default

Added tarantoolctl_layout config option to enable compatibility mode with tarantoolctl artifacts layout. If this option is set to `true`, `tt` will not create sub-directories for runtime artifacts such as control socket, pid file and log file. This option affects only single instance applications.
Here is manual testing of tt & tarantoolctl:
```
~# tarantoolctl start app1
Starting instance app1...
Forwarding to 'systemctl start tarantool@app1'
~# tarantoolctl status app1
Forwarding to 'systemctl status tarantool@app1'
● tarantool@app1.service - Tarantool Database Server
Loaded: loaded (/lib/systemd/system/tarantool@.service; enabled; vendor preset: enabled)
Active: active (running) since Wed 2023-02-08 15:20:11 MSK; 4s ago
~# tt status app1
• app1: RUNNING. PID: 142492.
~# tt connect app1 …
```

tt: support tarantoolctl app files layout

---

CHANGELOG.md
cli/cmd/help.go
test/integration/help/test_help.py

Usage is now shown for all commands.
External commands is now not shown for commands without it.
Example with external command: 
```  
Utility for managing Tarantool packages and Tarantool-based applications
USAGE
tt [flags] <command> [command flags]
COMMANDS
build       Build an application in specified PATH (default ".")
...
version     Show Tarantool CLI version information
EXTERNAL COMMANDS
help	Description for external module help
List of passed args: --description
FLAGS
-c, --cfg string     Path to configuration file
...
-V, --verbose        Verbose output
EXAMPLES
$ tt version -L /path/to/local/dir
$ tt help -S -I
$ tt completion
Use "tt <command> --help" for more information about a command.
``` 
Example without external command: 
``` 
Utility for managing Tarantool packages and …
```

help: fix output

---

cli/init/init.go
cli/init/init_test.go
test/integration/init/test_init.py

If `init` finds existing tarantoolctl config file, tt env configuration will have `tarantoolctl_layout` field set to True.

init: init tarantoolctl layout field

---

cli/install/Dockerfile.tnt.build
cli/install/install.go
cli/pack/templates/Dockerfile.pack.build
test/integration/install/test_install.py

- Use devnull instead of pipe for stdout.
- Update Ubuntu docker image version to avoid build errors related for no-pic libgomp.a.
- Update cmake and install additional dependencies for building the latest tarantool version.

Fix install test hang

---

CHANGELOG.md
cli/cmd/connect.go
cli/cmd/connect_test.go

Only `:@/` are forbidden to avoid confusion when parsing a URI.

connect: allow more characters for URI credential

---

cli/pack/templates/Dockerfile.pack.build

This patch is partial, everywhere we call docker we must pass default platform (linux/amd64). Without this patch tt pack fail to build artefact on M1

Implicit platform for docker image

---

CHANGELOG.md
cli/install/install.go

A user can specify make flags for tarantool building by using MAKEFLAGS environment variable. Do not append any make options if MAKEFLAGS is set.
Manual tests:
```
$ MAKEFLAGS="-j1" tt -V install tarantool
[  2%] Creating directories for 'openssl'
[  4%] Performing download step (download, verify and extract) for 'openssl'
-- Downloading...
```
```
$ MAKEFLAGS="-j4" tt -V install tarantool
[  8%] Creating directories for 'zlib'
[  8%] Creating directories for 'openssl'
[  8%] Creating directories for 'icu'
[  8%] Creating directories for 'ncurses'
[ 16%] Performing download step (download, verify and extract) for 'zlib'
[ 16%] Performing download step (download, verify and extract) for 'icu'
[ 16%] Performing download step (download, verify and extract) for 'ncurses'
[ 16%] Performing …
```

install: check if MAKEFLAGS is set

---

CHANGELOG.md
cli/cmd/connect.go
cli/codegen/generate_code.go
cli/connect/connect.go
cli/connect/console.go
cli/connect/language.go
cli/connect/lua/console_eval_func_body.lua
cli/connect/lua/eval_func_body.lua
cli/running/running.go
test/integration/connect/test_connect.py

A usage examples:
```bash
$ tt connect URI -f print.lua 1 2 3
$ echo "print(...)" | tt connect URI -f- 1 2 3
$ echo "print(...)" | tt connect URI -f- -- -flag 1 2 3 $ echo "print(...)" | tt connect URI -f- 1 2 -- -flag
```
Closes #256

connect: add ability to pass arguments to a script

---

CHANGELOG.md
README.rst
cli/cmd/binaries.go
cli/cmd/install.go
cli/cmd/root.go
cli/cmd/uninstall.go
cli/install/install.go
cli/list/list.go
cli/list/list_test.go
cli/list/testdata/bin/tarantool
cli/pack/deb.go
cli/pack/rpm_header.go
cli/search/bundle.go
cli/search/search.go
cli/uninstall/uninstall.go
cli/uninstall/uninstall_test.go
cli/version/version_tools.go
cli/version/version_tools_test.go
test/integration/binaries/bin/tarantool
test/integration/binaries/test_binaries.py

Added binaries command. It prints installed binaries.
Example output:
```
List of installed binaries:
• tt:                      
master
3.1.0
2.10.1
2.8.1
1.0.1
0.3.0
0.2.0
0.1.0
• tarantool:               
master
2.10.4 [active]
2.8.1
```
Closes #196

tt: add binaries command

---

cli/rocks/rocks.go
test/integration/rocks/test_rocks.py

--only-server rocks option can be provided using two formats: --only-server <server> and --only-server=<server>. Need to support both.

rocks: support only-server opt different formats

---

CHANGELOG.md
cli/create/builtin_templates/templates/cartridge/MANIFEST.yaml
cli/create/builtin_templates/templates/cartridge/init.lua.tt.template
test/integration/cartridge/test_cartridge.py
test/integration/create/test_create.py

The patch adds a configurable variable `cluster_cookie` for the cartridge template.
Closes #244
`secret-cluster-cookie` is a default value:
https://github.com/tarantool/cartridge/blob/892e25198d73204433ddb857ddafa116afafcd52/cartridge.lua#L57

create: add variable cluster_cookie for cartridge

---

CHANGELOG.md
cli/cmd/uninstall.go
cli/install/install.go
cli/list/list.go
cli/search/const.go
cli/search/search.go
cli/uninstall/uninstall.go
test/integration/uninstall/test_uninstall.py

After the patch `tt uninstall` does not ask version if only one version of a program is installed.
Closes #222

uninstall: don't ask version if only one

---

cli/list/list.go
test/integration/binaries/test_binaries.py

Changed error message, so it is more understandable for user
Previously:
```
f.terekhin@f-terekhin tt % ./tt binaries
⨯ error reading directory "/opt/tarantool/bin": open /opt/tarantool/bin: no such file or directory
```
Now:
```
f.terekhin@f-terekhin tt % ./tt binaries
⨯ there are no binaries installed in this environment of 'tt'
```

binaries: change error message

---

cli/cmd/binaries.go
cli/cmd/build.go
cli/cmd/check.go
cli/cmd/clean.go
cli/cmd/common.go
cli/cmd/common_test.go
cli/cmd/create.go
cli/cmd/install.go
cli/cmd/instances.go
cli/cmd/pack.go
cli/cmd/restart.go
cli/cmd/run.go
cli/cmd/start.go
cli/cmd/status.go
cli/cmd/stop.go
cli/cmd/uninstall.go
test/integration/check/test_check.py
test/integration/cli/test_launch.py
test/integration/instances/test_instances.py
test/integration/run/test_run.py
test/integration/uninstall/test_uninstall.py

The check has been added for:
- binaries
- build
- check
- clean
- create
- install
- instances
- pack
- restart
- run
- start
- status
- stop
- uninstall
Closes #371
I'm not sure about the command list. I suggest to add commands in a review.

cmd: add config check for almost commands

---

CHANGELOG.md
cli/cmd/binaries.go
cli/cmd/build.go
cli/cmd/check.go
cli/cmd/clean.go
cli/cmd/common.go
cli/cmd/common_test.go
cli/cmd/create.go
cli/cmd/install.go
cli/cmd/instances.go
cli/cmd/logrotate.go
cli/cmd/pack.go
cli/cmd/restart.go
cli/cmd/run.go
cli/cmd/start.go
cli/cmd/status.go
cli/cmd/stop.go
cli/cmd/uninstall.go
test/integration/check/test_check.py
test/integration/cli/test_launch.py
test/integration/instances/test_instances.py
test/integration/run/test_run.py
test/integration/uninstall/test_uninstall.py

The check has been added for:
- binaries
- build
- check
- clean
- create
- install
- instances
- logrotate
- pack
- restart
- run
- start
- status
- stop
- uninstall
Closes #371
The patch does not affect:
-  cartridge
-  cat
-  cfg
-  completion
-  connect
-  coredump
-  daemon
-  help
-  init
-  play
-  rocks 
-  search
-  version
I'm not sure about the command list. I suggest to add commands in a review.

cmd: add config check for almost all commands

---

CHANGELOG.md
cli/cartridge/extra/006_consider_tt_run_dir.patch
cli/cmd/root.go
cli/configure/configure.go
magefile.go
test/integration/cartridge/test_cartridge.py
test/integration/cfg/test_dump.py

The command will use tt environment run dir path for searching control sockets.
Manual tests:
```
$ tt init
• Found existing config '.cartridge.yml'
• Environment config is written to 'tt.yaml'
$ tt start
• Starting an instance [myapp:s2-replica]...
• Starting an instance [myapp:stateboard]...
• Starting an instance [myapp:router]...
• Starting an instance [myapp:s1-master]...
• Starting an instance [myapp:s1-replica]...
• Starting an instance [myapp:s2-master]...
$ tt cartridge replicasets setup --bootstrap-vshard
• Set up replicasets described in /home/user/myapp/replicasets.yml
• router... CREATED
• s-1... CREATED  
• s-2... CREATED  
• Replicasets are set up successfully
• Bootstrap vshard task completed successfully, check the cluster status
$ tt cartridge replicasets list
• Current …
```

cartridge: improve run dir path detection

---

.github/workflows/full-ci.yml
magefile.go
test/integration/ee/test_ee_install.py
test/integration/ee/test_ee_search.py
test/pytest.ini

With this patch:
- added integration tests for search/install tarantool-ee
- added a new pytest tag for ee tests
- included ee tests in full-ci target
Closes #357

ee: add ee integration tests

---

.github/workflows/publish.yml
.goreleaser.yml

This patch adds a step for autocompletion scripts generating in CI before package publishing jobs. 
Those scripts get packed into tt packages for further distribution.
Closes #399

tt: enable shell completion scripts after installation

---

CHANGELOG.md
cli/cmd/install.go
cli/cmd/uninstall.go
cli/install/install.go
cli/uninstall/uninstall.go
test/integration/ee/test_ee_install.py
test/integration/install/test_install.py
test/integration/uninstall/test_uninstall.py

tt install uses first cli arguments as a program name to install. This leads to difficulties with cli options separation by program name. Transform program names to sub-commands of tt install to make CLI more convenient.

install: make sub-commands from program names

---

README.rst

Before this commit, we show the status of the "Test" workflow, but gets a link to the "Full CI" workflow.

doc: fix "Full CI" badge

---

cli/cmd/install.go
cli/install/install.go
cli/install/install_test.go

This patch fixes the behavior by permissions checking, now we ignore the directory check if it doesn't exist.
Follow up #413

install: check include directory permission before it's mutation

---

CHANGELOG.md
cli/cmd/install.go
cli/install/install.go
test/conftest.py

Added new option --dynamic for tt install tarantool command. This options enables dynamic linking for building tarantool executable.

install: support of tarantool non-static build

---

CHANGELOG.md
cli/install/install.go
cli/install/install_test.go

`tt install tarantool` without version specification now installs the latest release.

install: get latest release

---

CHANGELOG.md
cli/connect/console.go

Fixed terminal brake after os.exit() in tt connect session. Have done it by adding workaround for the bug(c-bata/go-prompt#228) in case of executing os.exit().
Proof:
Terminal 1:
```
tarantool> better0fdead@better0fdead:~/.local/share/Trash$ tarantool
Tarantool 2.11.0-entrypoint-635-g5a38c5c90
type 'help' for interactive help
tarantool> box.cfg{listen=3305}
2023-04-27 12:44:48.029 [34240] main/103/interactive I> Tarantool 2.11.0-entrypoint-635-g5a38c5c90
2023-04-27 12:44:48.029 [34240] main/103/interactive I> log level 5
2023-04-27 12:44:48.030 [34240] main/103/interactive I> wal/engine cleanup is paused
2023-04-27 12:44:48.030 [34240] main/103/interactive I> mapping 268435456 bytes for memtx tuple arena...
2023-04-27 12:44:48.030 [34240] main/103/interactive I> Actual slab_alloc_factor …
```

connect: fix terminal after executing os.exit()

---

cli/cmd/daemon.go
cli/cmd/status.go
cli/process_utils/process_utils.go
cli/running/running.go
cli/status/status.go
test/integration/daemon/test_daemon.py
test/integration/running/test_running.py
test/utils.py

Made the output of the status command as a table.
Have done it using tabwriter from the standard library. Since tabwriter does not support ANSI escape codes, I need to remove extra spaces from the table header to use colored text in the second column of the table.
Closes #197

status: make the output of the command as a table

---

cli/status/status.go

Fixed the following issue with short app names:
```
../../tt/tt status app2
INSTANCE     ST              PID
app2         NOT RUNNING 
```
After the fix:
```
$ ../../tt/tt status
INSTANCE            STATUS          PID
app1:s1-master      RUNNING         50733
app1:s1-replica     RUNNING         50734
app1:s2-master      RUNNING         50735
app1:s2-replica     RUNNING         50738
app1:stateboard     RUNNING         50749
app1:router         NOT RUNNING     
app2                NOT RUNNING     
$ ../../tt/tt status app2
INSTANCE     STATUS          PID
app2         NOT RUNNING
```

status: fix truncated column name

---

CHANGELOG.md
cli/build/local.go
test/integration/ttbuild/test_build.py

Hide building output if there are no errors.
tt build re-worked to redirect stdout to /dev/null in case of no -V.
Closes #450.

build: hide building output if there are no errors.

---

CHANGELOG.md
cli/cmd/start.go
test/integration/running/test_running.py

Before this patch, starting an already running instance did not stop the existing process. 
As a result, the PID file of the existing process was being overwritten by the new start command. 
This led to the situation where it was impossible to control the old process, as the new one was already started. 
Additionally, if the old instance had allocated a port, the new process was unable to allocate it again and failed without the possibility of reallocation without manual killing of the existing process.
Closes #451

running: avoid starting an already running instance

---

CHANGELOG.md
cli/configure/configure.go
test/integration/rocks/test_rocks.py

If tt.repo.rocks is a relative path, tt rocks fails to use it if current working directory is not tt config location. The solution is to use rocks path relative to config location and not current working dir.

rocks: fix tt rocks install failure with local repo

---

CHANGELOG.md
README.md
cli/cmd/build.go
cli/cmd/clean.go
cli/cmd/connect.go
cli/cmd/internal/completion.go
cli/cmd/logrotate.go
cli/cmd/restart.go
cli/cmd/start.go
cli/cmd/status.go
cli/cmd/stop.go
cli/running/instance_filter.go
cli/running/instance_filter_test.go
cli/running/running.go

Make autocomplete smart.
For commands, which argument is APP|INSTANCE,
smart auto-complete basically shows:
1) Suitable apps, in case of the pattern doesn't contain delimiter `:`.
2) Suitable instances, otherwise.
Suitable means:
1) `tt start`: inactive apps (which has any no running instance) / inactive instances.
2) `tt stop`: active apps (which has any running instance) / active instances.
3) `tt restart`: same as `tt stop`.
4) `tt connect`: same as `tt stop`.
5) `tt build`: apps.
6) `tt clean`: apps / instances.
7) `tt logrotate`: same as `tt clean`.
8) `tt status`: same as `tt clean`.
Closes https://github.com/tarantool/tt/issues/467.

tt: smart autocomplete.

---

CHANGELOG.md
cli/connect/console.go

Fixed crash on `\q` input in `tt connect`.
In this case, instance returns an empty response,
add a check for this.
Closes #476

connect: fix crash on `\q`

---

CHANGELOG.md
cli/cmdcontext/cmdcontext.go
cli/rocks/rocks.go
cli/rocks/rocks_test.go
cli/util/util.go
cli/util/util_test.go
test/integration/rocks/test_rocks.py

Rocks local repository path and tarantool installation prefix path can be specified using environment variables. TT_CLI_REPO_ROCKS variable is used if it is set and there is no repo.rocks in tt config or repo.rocks directory does not include repository manifest.
TT_CLI_TARANTOOL_PREFIX variable is used for build, rocks commands if it is set and tarantool executable is found in PATH.
Closes #471

rocks: consider environment for some paths

---

CHANGELOG.md
cli/connect/console.go
cli/connect/history.go
cli/connect/history_test.go

Reworked operations with console history in `tt connect`
to be consistently with tarantool console history.
i.e.:
1) When a new command appears, it completely
rewrites the history file.
2) When writes history, it uses format with
timestamps.
3) Added parsing of timestamps history format.
Parsing mode (with timestamps or not) switches
in dependency of the history file content.
Closes https://github.com/tarantool/tt/issues/478, https://github.com/tarantool/tt/issues/426

connect: make console history consistent

---

cli/create/builtin_templates/templates/cartridge/init.lua.tt.template

This reverts commit 6ff6c869c0420ccdeb8addfa3e547e8fff8db3bc, which was committed by mistake.

revert "create: set `compat.fiber_slice_default` to `new` by default"

---

CHANGELOG.md
cli/create/builtin_templates/templates/cartridge/init.lua.tt.template

template: set `compat.fibert_slice_default` to `new` by default

---

CHANGELOG.md
cli/running/running.go
cli/util/util.go
cli/util/util_test.go
test/integration/running/multi_inst_app_no_init/instances.enabled/mi_app/instances.yml
test/integration/running/multi_inst_app_no_init/instances.enabled/mi_app/router.init.lua
test/integration/running/multi_inst_app_no_init/instances.enabled/mi_app/storage.init.lua
test/integration/running/multi_inst_app_no_init/tt.yaml
test/integration/running/test_running.py

It is possible to have an application without init.lua script. Script names can be specified using instances file. So if the directory contains instances file, it must be treated as a multi-instance application.

util: check for instances file in app dir

---

.github/workflows/full-ci.yml
.github/workflows/tests.yml
cli/docker/docker_integration_test.go
magefile.go
test/integration/install/test_install.py
test/integration/pack/test_pack.py
test/integration/rocks/test_rocks.py
test/pytest.ini

Switched testing on macOS to selfhosted runners.
Tests should no more be 'flaky'.
'full-ci 'is now 18 minutes faster.

ci: change full-ci-macos

---

cli/cmd/help.go
cli/cmd/root.go
cli/util/templates.go

Fix some issues with CLI.
Usage and allowed flags are now printed when invalid flags are entered, and exit code in this case is 1.
Screenshot for more info:
Closes #274

tt: fix CLI arguments/flags processing and help printing

---

.github/workflows/full-ci.yml
.github/workflows/tests.yml
cli/docker/docker_integration_test.go
cli/running/running_test_helpers.go
magefile.go
test/integration/install/test_install.py
test/integration/pack/test_pack.py
test/pytest.ini

Since docker daemon is now running on selfhosted
there is no need to use github runners anymore.
Switched full-ci macOS to selfhosted.
Closes #517

ci: switch macOS tests fully to selfhosted

---

cli/install/install.go
cli/install/install_test.go
test/integration/install/test_install.py

Added support for static build tree.
Also, changes in the installation logic:
Now, install creates directories and searches for headers only if the executable is found successfully.
Closes #525

install tarantool-dev: support for static build

---

test/integration/rocks/test_rocks.py

Deleted queue output check from tests since it is now not needed.
Closes #509

test: delete rocks output check

---

cli/connector/integration_test.go

Sometimes `connector` unit test fails with segfault due to `assert`, which does not stop a test in case of failure:
```
--- FAIL: TestConnect_Eval (0.00s)
integration_test.go:62: 
Error Trace:	integration_test.go:41
integration_test.go:62
integration_test.go:68
Error:      	Received unexpected error:
dial unix work_dir/console.control: connect: no such file or directory
Test:       	TestConnect_Eval
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10035f220]
```
Use the `require` to check the result of `net.Dial` and get protocol.

test: fix test segfault if net dial fails

---

cli/running/instance.go
cli/running/instance_test.go
cli/running/running_test_helpers.go
cli/running/test_app/dumb_test_app.lua
cli/running/test_app/dumb_test_run.lua
cli/running/test_app/log_check_test_app.lua
cli/running/watchdog.go
cli/running/watchdog_test.go

Watchdog tests rely on internal watchdog members to detect if an instance is started. But it's members can be uninitialized if watchdog did not start a process yet. The solution is to use external file for "instance is up" status check.

test: fix segmentation fault and races

---

CHANGELOG.md
cli/connect/console.go
cli/connect/input.go
cli/connect/input_test.go
go.mod
go.sum

Since a new version of the `tarantool/go-prompt` was released, it's usage has been updated in the `tt`.
- The module has been renamed. See https://github.com/tarantool/go-prompt/commit/8289fd9b72d9749cc6ec6e94728ca48492ccacfb
- The terminal failure after exit was fixed, so `stty sane` has been removed. See https://github.com/tarantool/go-prompt/commit/85a5ca7c72f75d94e6b5bcd237a9a2ac3d41b142
- Manual pushes to the prompt history have been added to handle multi-line commands correctly. See https://github.com/tarantool/go-prompt/commit/d4fc71bf3bfe9fda0edf6e7ec4cbdc45a9a4f958
- Functions 'prompt.GoLeftWord' and 'prompt.GoRightWord' are now used for word navigation. See https://github.com/tarantool/go-prompt/commit/cd83a88dd4a9d47f45c085029282fd62a16d9563
- `prompt.OptionReverseSearch` has …

connect: update go-prompt

---

.github/workflows/full-ci.yml

* Use `pull_request_target` for tests with secrets.
* Don't restart tests with secrets for external repositories automatically on `synchronize` action.
Closes #551

ci: fix full-ci tests

---

CHANGELOG.md
cli/cmd/pack.go
cli/pack/common.go
cli/pack/pack.go
test/integration/pack/test_pack.py

Add flag `--without-modules` to `tt pack` which allows not to take external modules into the bundle.
Closes #289

pack: add flag `without-modules` to `tt pack`

---

cli/connect/console.go
test/integration/connect/test_connect.py

`console.prompt` can be nill in the case of calling the executor without a prompt, so a check has been added.
Also, the return type of `getExecutor` has been changed to to make it clearer, that the executor can be used not only with a prompt.

connect: fix nil pointer dereference

---

cli/version/version_tools.go
cli/version/version_tools_test.go

Tarantool Enterprise version includes gc suffix in version string. Version parse fails to parse such versions. Fix it by adding supported suffixes in regexp.

tt: fix version parsing with GC suffix

---

CHANGELOG.md
cli/connect/console.go
cli/connect/shortcuts.go
test/integration/connect/test_connect.py

Add command `\shortcuts` listing all available shortcuts and hotkeys in go-prompt.
Closes https://github.com/tarantool/tt/issues/541

`connect`: add `\shortcuts` command

---

cli/pack/common.go
test/integration/pack/test_pack.py

Version from git was only taken if packing an application from the current directory. But since in `compat` mode we can pack only one application, we can use this application name to get git version from the application directory.

pack: fix package version in cartridge-compact mode

---

cli/install/install.go

Th warning message does not have a space between sentences.

install: fix warning message text

---

cli/cmd/connect.go

Add lines with usage connect  commands in
`tt help connect`

`help`: add available commands list in connect

---

cli/running/lua/launcher.lua
cli/running/watchdog.go
test/integration/running/test_running.py
test/utils.py

Sometimes instance restart test fails on the system with a loaded CPU.
This failure is due to timeout waiting for the instance to restart.
Wait time is 5 second. Watchdog already has 5 seconds timeout before
restarting the instance. so the whole start time becomes 5s watchdog
timeout + instance start time. So test's 5 seconds is not enough.
Increased wait time. Added log message about waiting for restart.
Added check for app status in test.

Fix restart test race

---

.gen_tarballs.sh
.github/workflows/publish.yml

Install mage from source as on Linux and on Mac for test workflows. It prevents from installing dependencies, which are not required.

ci: fix publish workflow error on mac

---

cli/cluster/config.go
cli/cluster/config_test.go

Before the patch Config.Merge() lost empty maps values.

cluster: fix merging configs with empty instances

---

CHANGELOG.md
cli/pack/common.go
cli/pack/common_test.go
test/integration/pack/test_pack.py

`--with-binaries` flag was only considered without `--cartridge-compat` flag. Fixed this bug.
Also, in compat mode, `bin` directory is always set to `.`. This is because in case of `cartridge`, archive does not have any additional directories rather than application directory. `cartridge cli` packs binaries into `root`.
`tarantool` binary after `pack` now always named `"tarantool"`.
Closes https://github.com/tarantool/tt-ee/issues/74

pack: fix `--with-binaries` flag not working in cartridge-compact mode

---

CHANGELOG.md
cli/cmd/connect.go
cli/connect/connect.go
cli/connect/console.go

Use connect target for interactive command prompt. Examples:
```
tt connect app1:router
• Connecting to the instance...
• Connected to app1:router
app1:router>
tt connect localhost:3301
• Connecting to the instance...
• Connected to localhost:3301
localhost:3301>
tt connect ./var/run/app1/router/router.control
• Connecting to the instance...
• Connected to ./var/run/app1/router/router.control
./var/run/app1/router/router.control>
```
Closes #573

connect: change default prompt

---

cli/rocks/extra/hardcoded.lua
cli/rocks/rocks.go

Relying on PWD var means that tt invocation from  other code require setting of the PWD variable, making chdir is not enogh. Call getwd instead of using getring PWD. getwd call internally also checks PWD environment variable.

rocks: replace $PWD with getwd call

---

CHANGELOG.md
cli/cmd/pack.go
cli/pack/docker.go
cli/pack/pack.go
test/integration/pack/test_pack.py

Add a new `tt pack` flag `--tarantool-version` to specify tarantool version for pack in docker. It is supported only with `--use-docker` enabled.
If `tt` can not parse given version, or this version does not exist, an error is thrown.
Closes #353

pack: add a flag to pass tarantool version for pack in docker

---

cli/running/process_controller_test.go
cli/running/testdata/signal_handling.py

Child process exits after stdin descriptor is closed, because `read` is used as interruptible sleep. Sometimes the unit-test sends SIGINT to already stopped process, which causes test failure. The solution is to create a separate script to test signal handling whithout sleep using bash read call.

tt: fix race in running package unit test

---

cli/cluster/file_test.go

Make sure file permissions are not updated after publishing.

cluster: fix file publisher unit test

---

CHANGELOG.md
cli/rocks/extra/wrapper.lua
go.mod
go.sum
test/integration/rocks/test_rocks.py

tt rocks admin implements luarocks-admin commands tree.
Gopher-lua is bumped to 71163b697a8f07f32b7f6d2898726b198f25ba20:
https://github.com/yuin/gopher-lua/commit/71163b697a8f07f32b7f6d2898726b198f25ba20
Before this fix, gopher-lua could corrupt files (affected on tt admin
remove).
A pull request was also made to the upstream to support the 'remove'
command with the 'file' protocol:
https://github.com/luarocks/luarocks/pull/1536
Closes #563

rocks: added admin commands tree

---

cli/pack/common.go
cli/pack/docker.go
cli/pack/templates/Dockerfile.pack.build

Copy tarantool include files from tarantool build image. Install required dependencies for building rocks.

pack: fix packing in docker

---

CHANGELOG.md
cli/cmd/root.go
cli/cmd/root_test.go
test/integration/cli/test_launch.py
test/integration/help/test_help.py

This patch fixes incorrect behavior of parsing global flags of the tt
command.
E.g: `tt --cfg some_file install tarantool --cfg other_file`
In this case, the result of the second cfg option was taken and the
error was thrown that there was no such option in install.
This behavior is incorrect and has been fixed. The value of the overridden
option will now be ignored.
Now global flags are required to be positioned only before child
commands:
OK:
`tt --cfg tt.yaml install ...`
Not OK:
`tt install ... --cfg tt.yaml`
Closes #521

cli: fix flag parsing issues

---

CHANGELOG.md
test/integration/rocks/test_rocks.py

The behavior of io.popen() is different in lua and gopher-lua. See: https://github.com/yuin/gopher-lua/issues/459
The fix uses a temporary fix in our luarocks fork.
Closes #612

rocks: fix --verbose option

---

README.md
cli/cmd/cluster.go
doc/examples.md

It also fixes help messages for `tt cluster show` and `tt cluster publish`.

doc: add examples for tt cluster

---

CHANGELOG.md
cli/version/version.go
magefile.go

If there were commits after the tag, this information will be shown. Otherwise it will be the usual format.
Example:
$  git tag v5.6.7
$  mage build
Building tt...
Apply cartridge-cli patches...
$  ./tt version
Tarantool CLI version 5.6.7, linux/amd64. commit: b69e586 
$  git tag -d v5.6.7
Deleted tag 'v5.6.7' (was b69e586)
$  mage build
Building tt...
Apply cartridge-cli patches...
$  ./tt version
Tarantool CLI version 1.3.0, linux/amd64. commit: b69e586 (v1.3.0-9-b69e586)

version: add commits since tag info

---

CHANGELOG.md
cli/cmd/connect.go

If a user specifies creds in connect string, use
cleaned up URI for console title and prompt.
```
$ tt connect admin:admin@localhost:3301
• Connecting to the instance...
• Connected to localhost:3301
localhost:3301>
$ tt connect localhost:3301
• Connecting to the instance...
• Connected to localhost:3301
localhost:3301>
```

connect: change console title and prompt

---

CHANGELOG.md
cli/list/list.go

tt binaries do not list installed tarantool-ee packages.
Closes #653

binaries: tarantool-ee binaries not shown.

---

CHANGELOG.md
cli/cmd/install.go
cli/cmd/search.go
cli/install/install.go
cli/search/search.go
cli/search/tntio_api.go
test/integration/ee/test_ee_install.py

Examples:
`tt search tarantool-ee --dev`
`tt search tarantool-ee --dev --version master`
`tt search tarantool-ee --dev --version 2.11`
`tt install tarantool-ee x.y.x --dev`
Closes #650

tarantool-ee: search and install development build

---

.github/actions/static-code-check/action.yml
.github/workflows/full-ci.yml
.github/workflows/tests.yml
test/requirements.txt

We are using a method that was deprecated in the
importlib-metadata v5.0.0 release, let's lock the library version used.

test: add yet one locked python dependency

---

cli/cmd/connect.go
cli/connect/const.go
cli/connect/uri.go
cli/connect/uri_test.go

We need this environment variables and functions for `tt-ee` modules to unify the behavior across modules.
Part of https://github.com/tarantool/roadmap-internal/issues/281

connect: make user/pass environment variables constants and helper functions public

---

CHANGELOG.md
cli/cluster/cmd/publish.go
cli/cluster/cmd/show.go
cli/cmd/cluster.go
cli/connect/const.go
test/integration/cluster/test_cluster.py

The patch adds etcd credentials pass via environment variables and command flags.
Part of https://github.com/tarantool/roadmap-internal/issues/281

cluster: add missed credentials pass methods

---

CHANGELOG.md
README.md
cli/running/running.go
cli/running/running_test.go
cli/running/script_instance.go
cli/running/testdata/instances_enabled/cluster_app/instances.yml
doc/examples.md
test/integration/running/multi_inst_app/instances.yml
test/integration/running/small_cluster_app/config.yaml
test/integration/running/small_cluster_app/instances.yml
test/integration/running/test_running.py
test/integration/running/test_running_cluster.py

This patch adds changes to the `instances.yml` parsing logic:
1. Ignore app-instance delimiters for Tarantool 3.0 instances.
2. Don't use dash as an app-instance delimiter. At the same time, `cartridge_app-stateboard`
treated as a special case.
1. [x] tests
2. [x] changelog
3. [x] docs  
Closes #565

running: changes in `instances.yml` parsing logic

---

cli/cluster/etcd_test.go

Increase timeout delta to fix flaky test.

test: increase timeout delta

---

test/integration/install/test_install.py

Some tests were disabled due to incompatibility changes. Enable them back and make them more robust.

test: enable install tests back

---

CHANGELOG.md
cli/checkpoint/checkpoint.go
cli/checkpoint/lua/cat.lua

Now ``tt cat`` prints logs into stderr not stdout.
Closes #624

``cat``: print logs into stderr

---

cli/cmd/connect.go

The patch removes an invalid default value for TLS flags. At now the default value `connect.DefaultLanguage.String()` does not cause any problem because it is "".

connect: fix TLS flags setup

---

.github/workflows/full-ci.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
.github/workflows/update.yml

Some vulnerabilities were found in previous versions of go. Let's switches to the latest release 1.21.

ci: update go version to >=1.21.2

---

CHANGELOG.md
cli/cmd/connect.go

This patch changes the behavior of `tt connect` auto-completion, when there are no running apps now. 
In this case `tt connect` completion should show directories and files.

connect: change completion behavior

---

cli/cmd/start.go

Set separate process group for watchdog process, so it will not be killed by a closed ssh session.

start: separate pgid for watchdog process

---

test/integration/running/cluster_crud_app/localcfg.lua
test/integration/running/cluster_crud_app/router.lua

Since commit [1], it is forbidden to call box.cfg as a part of vshard.router.cfg: it is expected that user will separate their setups. This patch should satisfy both older and newer vshard versions.
1. https://github.com/tarantool/vshard/commit/bc1c3c46ee474640ff1fe7dceacda45f7290c368

test: fix setup with master vshard

---

CHANGELOG.md
cli/cluster/cluster.go
cli/cluster/cmd/publish.go
cli/cluster/cmd/show.go
cli/cluster/etcd.go
cli/cluster/etcd_test.go
cli/cluster/integration_test.go
cli/cmd/cluster.go
test/integration/cluster/test_cluster.py

Title: new argument for `tt cluster show` and `tt cluster publish`
The patch adds a new argument `key` that could be specified via etcd URI:
* key - a target configuration key in the prefix.
A user can now perform operations (`show` and `publish`) on individual keys in etcd, not just for entire prefixes.
As example:
```
$ tt cluster show https://user:pass@localhost:2379/prefix?key=target
```

cluster: add `key` argument to URI

---

cli/cmd/root.go
cli/cmd/start.go
cli/cmdcontext/cmdcontext.go
cli/configure/configure.go
cli/integrity/dummy_repository.go
cli/integrity/integrity.go
cli/integrity/integrity_test.go
cli/integrity/repository.go
cli/modules/run.go
cli/running/cluster_instance.go
cli/running/cluster_instance_test.go
cli/running/running.go
cli/running/script_instance.go
cli/running/script_instance_test.go
cli/running/watchdog.go
cli/running/watchdog_test.go

This patch adds necessary scaffolding for performing integrity checks,
along with an appropriate instrumentation of operations with files
that must be scrutinized before working with them.

integrity: scaffolding for integrity check

---

magefile.go

Debug build can be performed with `mage build:debug` command. Default build type is release.
Building example:
```
$ mage build && readelf -S ./tt | grep debug
Building release tt...
Apply cartridge-cli patches...
$ mage build:debug && readelf -S ./tt | grep debug
Building debug tt...
Apply cartridge-cli patches...
[13] .debug_abbrev     PROGBITS         0000000000000000  013e9000
[14] .debug_line       PROGBITS         0000000000000000  013e9135
[15] .debug_frame      PROGBITS         0000000000000000  015554d7
[16] .debug_gdb_s[...] PROGBITS         0000000000000000  015aeac4
[17] .debug_info       PROGBITS         0000000000000000  015aeaf1
[18] .debug_loc        PROGBITS         0000000000000000  01832513
[19] .debug_ranges     PROGBITS         0000000000000000  01a1ecb9
```

tt: add tt debug build support

---

CHANGELOG.md
cli/cmd/run.go
cli/running/cluster_instance.go
cli/running/instance.go
cli/running/running.go
cli/running/script_instance.go
test/integration/run/test_run.py

Disabled flag parsing for 'run' command.
Done that so there will be no more differences in behaviour between 'tt run' and 'tarantool'.
e.g positional flag parsing, missing/more flags than tarantool has.

run: disable flag parsing

---

cli/cartridge/extra/008_increase_replicasets_bootstrap_attempts.patch
magefile.go

We have flaky tests with Cartridge on MacOS. It looks like not enough attempts are being made to bootstrap the vshard application.
This patch doubles the number of attempts.
Closes #728

cartridge: increase bootstrap attempts

---

cli/replicaset/cartridge.go
cli/replicaset/cconfig.go
cli/replicaset/cmd/status.go
cli/replicaset/custom.go
cli/replicaset/discovery.go
cli/replicaset/instance.go

The patch extracts two methods into the `replicaset` subpackage:
* `DiscoveryApplication(app RunningCtx, orchestrator Orchestrator)` to discovery replicasets information for an application running context.
* `DiscoveryInstance(evaler Evaler, orchestrator Orchestrator)` to discovery replicasets information for a connection.
An orchestrator type can be forced manually using the second argument or you can use OrchestratorUnknown for automatic mode.

replicaset: extract discover methods

---

.github/workflows/update.yml

`mage generate` requires `stringer` tool for code generation.

ci: install stringer tool for update

---

go.mod
go.sum

The bump needed to fix svacer issues.

build(deps): bump go-tarantool to v1.12.2

---

.github/actions/prepare-ce-test-env/action.yml
CHANGELOG.md
cli/cmd/create_test.go
cli/codegen/generate_code.go
cli/create/builtin_templates/builtin_templates.go
cli/create/builtin_templates/templates/vshard_cluster/MANIFEST.yaml
cli/create/builtin_templates/templates/vshard_cluster/config.yaml.tt.template
cli/create/builtin_templates/templates/vshard_cluster/instances.yaml.tt.template
cli/create/builtin_templates/templates/vshard_cluster/router.lua
cli/create/builtin_templates/templates/vshard_cluster/storage.lua
cli/create/builtin_templates/templates/vshard_cluster/{{.name}}-scm-1.rockspec.tt.template
cli/running/testdata/instances_enabled/cluster_app/config.yml
cli/templates/internal/engines/builtin_funcs.go
cli/templates/internal/engines/builtin_funcs_test.go
cli/templates/internal/engines/go_text_engine.go
cli/templates/internal/engines/go_text_engine_test.go
test/integration/connect/test_connect.py
test/integration/connect/test_output_format_app/test_app.lua
test/integration/create/test_create.py
test/integration/replicaset/test_ccluster_app/config.yaml
test/integration/running/cluster_app_changed_defaults/config.yaml
test/integration/running/cluster_crud_app/config.yaml
test/integration/running/small_cluster_app/config.yaml
test/utils.py

This patch introduces built-in `vshard_cluster` template,
which uses tarantool 3.0 config.

create: add built-in vshard cluster template

---

cli/search/search.go

Fix regular expression for cutting version from SDK bundle names. The revision number in 3.0 consists of two numbers.

search: sdk 3.0 was missing

---

CHANGELOG.md
cli/replicaset/cartridge.go
cli/replicaset/discovery.go
cli/replicaset/lua/cartridge/get_topology_replicasets_body.lua

Now, discovery prefers instances without critical issues during search.
Currently, there is no way to determine whether an instance has been expelled from the replicaset. However, critical issues are likely to be the reason for expelling an instance. Also, expelling an instance leads to the critical issues with replication in some cases. Therefore, we can identify expelled instances based on indirect reasons.
Closes https://github.com/tarantool/tt/issues/747

replicaset: prefer cartridge instances without critical issues during discovery

---

cli/connector/integration_test.go
cli/replicaset/integration_test.go

This patch adds changes to the go integration tests:
* Wait for tarantool start longer: it was noticed that the timeout is too small for macos
* Don't use `log.Fatalf`: deferred code is not executed, which can lead to non stopped instance

test: increase timeouts

---

CHANGELOG.md
cli/rocks/extra/macosx.lua
cli/rocks/rocks.go

Added workaround to fix crashes on macOS: override of macosx.lua. It is not needed
and is a cause of crashes on macOs.
This workaround is not perfect and can be removed later.
Closes #640

rocks: fix macOs not working

---

CHANGELOG.md
cli/build/local.go
cli/build/syscall_wrapper_darwin.go
cli/build/syscall_wrapper_freebsd.go
cli/build/syscall_wrapper_linux.go
magefile.go

This patch fix build error:
cli/build/local.go:88:20: undefined: syscall.Dup2
cli/build/local.go:91:17: undefined: syscall.Dup2
cli/build/local.go:101:20: undefined: syscall.Dup2
syscall.Dup3 does not exists on darwin (OSX).
syscall.Dup2 does not exists on linux (aarch64).
So a syscall wrapper was added.
Part of #400

build: fix build on aarch64

---

CHANGELOG.md
cli/install/install.go

git checkout fails in tt install due to missing submodule. The solution is to checkout and init submodules separately.

install: fix checkout error

---

cli/cluster/cluster.go
cli/cluster/config.go
cli/cluster/config_test.go
cli/cluster/integration_test.go
cli/cluster/yaml.go
cli/cluster/yaml_test.go
go.mod
test/integration/cluster/test_cluster.py

Since v2 has unexpected artifacts like `on/off` to bool parsing, let's bump this dependency as it was changed in the v3.
Since v3 can parse maps to `map[string|any]string` depending on the weather, let's get rid of ambiguities performing converting to the `map[any]any`.

cluster: bump yaml to v3 

---

doc/examples.md

`listen` format is changed in latest tarantool version. Update the examples according to the changes.

doc: update cluster examples config format

---

CHANGELOG.md
cli/running/lua/launcher.lua

This patch fixes the `tt start` bug on FreeBSD:
`LuajitError: stdin:259: Undefined symbol "stdout"`

start: repairing instance launch on freebsd

---

cli/cluster/cmd/publish.go
cli/cluster/etcd.go
cli/cluster/etcd_test.go
cli/cluster/file.go
cli/cluster/file_test.go
cli/cluster/integration_test.go
cli/cluster/tarantool.go
cli/cluster/tarantool_test.go
cli/cluster/yaml.go
cli/cluster/yaml_test.go
cli/integrity/datacollector.go
cli/integrity/datapublisher.go
cli/replicaset/lua/cconfig/get_instance_topology_body.lua

This patch introduces several changes:
* add `mod_revision` field support to the cluster etcd/tcs publishers/collectors.
* fix a bug with tcs response decoding.
* use the option `box.info.ro` instead of the `box.cfg.read_only` to determine instance mode.
Part of https://github.com/tarantool/tt/issues/315

cluster: support revision 

---

CHANGELOG.md
cli/binary/list.go
cli/binary/list_test.go
cli/binary/testdata/no_symlink/tarantool
test/integration/binaries/test_list.py

If `tarantool` binary is not a symlink, try to execute it to get version. Use this version in versions list.
Here is an example of output if `tarantool` is a binary file (not a symlink):
```
$ ls -l bin
total 38176
-rwxr-xr-x 1 user user 39089200 фев 15 15:32 tarantool
$ tt binaries list
List of installed binaries:
• tarantool:               
3.1.0-entrypoint-83-gcb0264c3c [active]
```

binaries: fix list error if binary is not a link

---

cli/cmd/completion.go
cli/cmd/create.go

- Added `vshard_cluster` template  info for `create` command.
- Added an example of enabling bash completion for `completion` command.

Update help for `create` ang `completion` commands.

---

cli/running/running.go
lib/cluster/config.go
lib/cluster/config_test.go
lib/cluster/storages.go
lib/cluster/storages_test.go

This patch makes the handling of cluster.NotExistError unambiguous. There is one place where we return it by pointer, while in other places it's returned by value. Let's always return it by value.
Also, adds an ability to extract key from the config source. This will be convenient if, after retrieving keys using the DataCollector, we want to upload them back.

cluster: some improvements 

---

cli/pack/systemd_dir_test.go

Remove unnecessary files copying, directories creation. Replace wanterr check with existing `NoError` function.

pack: unit test refactor

---

README.md
doc/known_issues.md

Title: User should not to set `box.cfg.background = true` with `tt start`
`tt start` daemonizes a Tarantool process itself. The `box.cfg.background` setting does the same thing from a Tarantool process. These features conflict with each other. As a result, `tt status` shows an invalid status of a Tarantool instance, and it is unable to stop the instance with `tt stop`.
A user should never set `box.cfg.backround = true` in an application code that is started by `tt`.
Closes #780

doc: add a note about box.cfg.background usage

---

CHANGELOG.md
cli/cluster/cmd/replicaset.go
cli/cmd/cluster.go
cli/cmd/replicaset.go
cli/replicaset/cartridge.go
cli/replicaset/cartridge_test.go
cli/replicaset/cconfig.go
cli/replicaset/cconfig_test.go
cli/replicaset/cmd/common.go
cli/replicaset/cmd/demote.go
cli/replicaset/cmd/expel.go
cli/replicaset/cmd/promote.go
cli/replicaset/cmd/status.go
cli/replicaset/configsource.go
cli/replicaset/configsource_test.go
cli/replicaset/custom.go
cli/replicaset/custom_test.go
cli/replicaset/demote.go
cli/replicaset/discovery.go
cli/replicaset/eval.go
cli/replicaset/expel.go
cli/replicaset/lua/cartridge/edit_instances_body.lua
cli/replicaset/lua/cconfig/get_instance_topology_body.lua
cli/replicaset/orchestrators_test.go
cli/replicaset/promote.go
test/integration/cluster/test_cluster_demote.py
test/integration/cluster/test_cluster_expel.py
test/integration/cluster/test_cluster_promote.py
test/integration/replicaset/test_ccluster_app/init.lua
test/integration/replicaset/test_replicaset_expel.py

Title: new commands: `tt replicaset expel`, `tt cluster replicaset expel`
The patch introduces a new command for the `tt replicaset` module:
* `tt replicaset expel APP_NAME:INSTANCE_NAME` - to expel an instance from a cluster.
The command automatically determines a replicaset orchestrator. Currently, it supports:
* cartridge - the Cartridge orchestrator for Tarantool <= 2.
* config - the centralized config orchestrator for Tarantool >= 3.
Usage:
tt replicaset expel [--cartridge|--config|--custom] <APP_NAME:INSTANCE_NAME>
The example of execution:
```
$ tt replicaset expel myapp:instance-003
• Discovery application...
Orchestrator:      centralized config
Replicasets state: bootstrapped
• replicaset-001
Failover: off
Master:   single
• instance-001 …
```

replicaset: add `expel` command

---

CHANGELOG.md
cli/cmd/clean.go
test/integration/running/test_data_app/test_data_app.lua
test/integration/running/test_running.py
test/utils.py

Before this patch, `tt clean` could list files multiple times since it is possible that memtx_dir, wal_dir, vinyl_dir and log_dir are the same directory (and the first three are the same by default). It also had tried to removed them several times, which had resulted in `[ERR]` message in logs. This patch fixes the issue.
Closes #735

clean: fix attempt to remove files multiple times

---

.codespellrc
CHANGELOG.md
cli/cluster/cmd/failover.go
cli/cmd/cluster.go
test/integration/cluster/test_cluster_failover.py

Title: `tt cluster failover commands`
This patch adds new commands:
* tt cluster failover switch - switch master instance
* tt cluster failover switch-status - show master switching status
This commands works only with etcd based failover configuration.
Closes #822

failover: add supervised failover commands

---

CHANGELOG.md
cli/cmd/replicaset.go
cli/replicaset/cartridge.go
cli/replicaset/cartridge_test.go
cli/replicaset/cconfig.go
cli/replicaset/cconfig_test.go
cli/replicaset/cmd/common.go
cli/replicaset/cmd/status.go
cli/replicaset/cmd/vshard.go
cli/replicaset/custom.go
cli/replicaset/custom_test.go
cli/replicaset/lua/cartridge/bootstrap_vshard_body.lua
cli/replicaset/lua/cconfig/bootstrap_vshard_body.lua
cli/replicaset/vshard.go
test/cartridge_helper.py
test/conftest.py
test/integration/replicaset/test_replicaset_vshard.py
test/integration/replicaset/test_vshard_app/config.yaml
test/integration/replicaset/test_vshard_app/init.lua
test/integration/replicaset/test_vshard_app/instances.yaml
test/utils.py

Title: `tt replicaset vshard bootstrap` - bootstraps vshard in the cluster
This patch introduces new subcommand for the replicaset module.
`tt replicaset vshard` - manages vshard in the cluster.
`tt replicaset vshard bootstrap [--cartridge|--config|--custom] [flags] (<APP_NAME> | <APP_NAME:INSTANCE_NAME> | <URI>)`
* Bootstraps vshard in the replicaset.
* Cartridge: by fact, it is the clone of `cartridge-cli replicasets bootstrap-vshard`.
* Centralized config (3.0): lookups for the router in the cluster and calls `vshard.router.bootstrap()` on it.
Part of https://github.com/tarantool/tt/issues/316

replicaset: add `vshard bootstrap`

---

.github/workflows/full-ci.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
.github/workflows/update.yml
cli/cmd/replicaset.go
cli/replicaset/cmd/vshard.go

- Some common functions have been moved to separate packages, let's use it.
- CI: add missing `ref` parameters to checkout in full-ci workflow triggered by pull_request_target event.
- CI: fix actions/checkout version.

replicaset: use extracted functional

---

CHANGELOG.md
cli/pack/common.go
test/conftest.py
test/integration/pack/test_pack.py

If Tarantool is used from the current environment, the application build uses the resulting package temporary directory as the Tarantool include files path. However, this directory does not exist in the resulting package. Use the current environment for building the application.

pack: fix application build failure

---

.github/workflows/full-ci.yml
.github/workflows/tests.yml

Usage of `github.event.pull_request.number` unsafe because a user could update a pull request between approve and checkout.

ci: use `github.event.pull_request.head.sha` with `full-ci`

---

CHANGELOG.md
cli/cmd/log.go
cli/cmd/root.go
cli/tail/color.go
cli/tail/color_test.go
cli/tail/tail.go
cli/tail/tail_test.go
go.mod
go.sum
test/integration/log/test_log.py

`tt log` prints the last 10 lines of all instances logs by default. A user can specify an application or instance name and limit the number of lines using the `--lines` option.
Part of #251

log: log command initial implementation

---

CHANGELOG.md
cli/codegen/generate_code.go
cli/connect/connect.go
cli/connect/console.go
cli/connect/language.go
cli/connect/language_test.go
cli/connect/lua/console_eval_func_body.lua
cli/connect/lua/eval_func_body.lua
cli/formatter/node.go
cli/formatter/table.go
cli/formatter/unordered_map.go
cli/formatter/yaml.go
test/integration/connect/test_connect.py

Support format for Tarantool tuples. This support only works for Tarantool versions >= 3.2.
Closes https://github.com/tarantool/tt/issues/832
Title: Support Tarantool tuple format
This patch adds support for formatting Tarantool tuples. Installed Tarantool version must be >= 3.2. Otherwise, there will be no change.
Examples:
```
> f = box.tuple.format.new({{'id', 'number'}, {'name', 'string'}})
---
...
> t = box.tuple.new({1, 'Flint', true}, {format = f})
---
...
> \xt
> t
+----+-------+------+
| id | name  | col1 |
+----+-------+------+
| 1  | Flint | true |
+----+-------+------+
> box.space.customers:select()
+----+-----------+-----+
| id | name      | age |
+----+-----------+-----+
| 1  | Elizabeth | 12  |
+----+-----------+-----+
| 2  | Mary      | 46  | …
```

connect: support Tarantool tuple format

---

CHANGELOG.md
README.md
cli/cmd/enable.go
cli/cmd/root.go
cli/enable/enable.go
cli/enable/enable_test.go
cli/enable/testdata/test_app/init.lua
cli/enable/testdata/test_script/test.lua
test/integration/enable/test_app/init.lua
test/integration/enable/test_enable.py
test/integration/enable/test_script/test.lua

Title: `tt enable` creates a symbolic link in `instances_enabled` directory to a script or an application directory.
This patch adds new command.
`tt enable <APP_PATH> | <SCRIPT_PATH>` creates a symbolic link in `instances_enabled` directory
to a script or an application directory.
Examples:
Create a symbolic link in `instances_enabled` directory to a script:
```$ tt enable Users/myuser/my_scripts/script.lua```
Create a symbolic link in  `instances_enabled`directory to an application directory:
```$ tt enable ../myuser/my_cool_app```

tt: add enable module

---

CHANGELOG.md
cli/binary/switch.go
test/integration/binaries/test_switch.py

'switch tt' now works with 'x.x.x' version format.
Closes #876

switch: fix 'switch tt'

---

test/etcd_helper.py

Added default value to 'os.getenv()', so tests won't fail if 'ETCD_PATH' is not set.

test: fix 'etcd_helper'

---

CHANGELOG.md
cli/install/install.go
cli/util/errors.go
cli/util/util.go
test/integration/install/test_install.py

Fixed a bug related with case when program finishes with 0 status code in unsuccessful way.
To do this I edit returning type from `bool` to `error` in `programDependenciesInstalled` function to finish program with error exit code in right way on higher layer.
Closes #651

tt: fix returning status code on unsuccessful dependency install

---

CHANGELOG.md
cli/pack/common.go
cli/pack/rpm_const.go
test/integration/pack/test_pack.py

systemctl start fails for the instances packed by `tt pack` due to permissions error. `/var/<dir>/tarantool` has root:root owner:group which does not allows `tt` to check sub-directories. Set tarantool:tarantool permissions for `/var/<dir>/tarantool` directories. Do not create sub-dirs by default, they will be created on first start.

pack: fix artifacts directories owner:group

---

magefile.go

The tag enables usage of `msgpack/v5` libreary instead of `msgpack.v2`. It fixes decoding errors with msgpack extension types at the go-tarantool connector.
Part of https://github.com/tarantool/tt-ee/issues/151

build: add go_tarantool_msgpack_v5 build tag

---

CHANGELOG.md
cli/install/install.go
cli/uninstall/uninstall.go
cli/uninstall/uninstall_test.go
test/integration/uninstall/test_uninstall.py

It was impossible to uninstall tt by version without 'v' prefix using `tt unistall tt 1.2.0` for example because program checks version in binary file with prefix.
After the patch `tt uninstall` checks 'v' prefix before version and if it didn't find, adds for strings matching.
Closes #583

uninstall: fix removing tt by version

---

CHANGELOG.md
cli/cmd/replicaset.go
cli/replicaset/bootstrap.go
cli/replicaset/cartridge.go
cli/replicaset/cartridge_test.go
cli/replicaset/cconfig.go
cli/replicaset/cconfig_test.go
cli/replicaset/cmd/bootstrap.go
cli/replicaset/cmd/common.go
cli/replicaset/common.go
cli/replicaset/custom.go
cli/replicaset/custom_test.go
cli/replicaset/eval.go
cli/replicaset/lua/cartridge/get_instance_info_body.lua
cli/replicaset/lua/cartridge/get_topology_replicasets_body.lua
test/cartridge_helper.py
test/integration/cartridge/test_cartridge.py
test/integration/replicaset/test_replicaset_bootstrap.py
test/utils.py

Title: tt replicaset bootstrap bootstraps a Cartridge app or an instance
This patch adds new subcommand for the replicaset module.
tt replicaset bootstrap [flags] <APP_NAME|APP_NAME:INSTANCE_NAME> bootstraps a Cartridge cluster
or an instance.
The command combines two old cartridge-cli commands: setup and join.
Examples:
tt replicaset bootstrap cartridge_app bootstraps the cluster from the default
config file ("replicasets.yml" in the app directory), the file can be specified with --file option.
tt replicaset bootstrap --bootstrap-vshard cartridge_app bootstraps the cluster and vshard.
tt replicaset bootstrap --replicaset replicaset cartridge_app:inst joins the instance "inst" to the replicaset "replicaset".
Part of #316

replicaset: add bootstrap

---

test/conftest.py
test/etcd_helper.py
test/integration/cluster/test_cluster_demote.py
test/integration/cluster/test_cluster_promote.py
test/integration/cluster/test_cluster_publish.py
test/integration/cluster/test_cluster_show.py
test/integration/cluster/test_tcs_app/config.yaml
test/integration/connect/test_connect.py
test/integration/play/test_play.py
test/utils.py

There were integration tests for `tt cluster publish/show` only for `etcd` and weren't for Tarantool Config Storage.
Due to the same interface tests have been parametrised to do the same business logic for different storages.
Closes #716

test: add tests for tcs cluster publish/show

---

CHANGELOG.md
cli/cmd/replicaset.go
cli/cmd/start.go
cli/process_utils/process_utils.go
cli/replicaset/rebootstrap.go
cli/replicaset/rebootstrap_test.go
cli/running/running.go
test/cartridge_helper.py
test/conftest.py
test/integration/replicaset/test_replicaset_rebootstrap.py
test/utils.py
test/vshard_cluster.py

replicaset: add rebootstrap command

---

cli/cmd/pack.go

If the "--with-integrity-check" and "--without-binaries" flags was provided simultaneously `tt pack` works correctly.
After the patch this combination of flags became impossible due to safety reasons.
Part of https://github.com/tarantool/tt-ee/issues/210

pack: add error on impossible flags combination

---

CHANGELOG.md
cli/cmd/root.go
cli/cmdcontext/cmdcontext.go
cli/cmdcontext/cmdcontext_test.go
cli/configure/configure.go
cli/install/install.go
cli/version/version_tools.go
cli/version/version_tools_test.go
test/integration/cli/test_launch.py
test/integration/install/test_install.py

Fix impossibility of reinstalling latest version of master. Add additional checking if current binary file with the latest version. Also add to 'fixed' in CHANGELOG file and write integration test for it.
Closes #690

install: fix impossibility of reinstalling master

---

test/integration/install/test_install.py

It was impossible to test detection of latest version in master branch due to the same commit hash.
After the patch tests create executable file with emulation of work 'tt verison --commit' to avoid this problem.

install: fix tests failure in master branch

---

CHANGELOG.md
cli/cmd/start.go
cli/daemon/api/http.go
cli/daemon/httpserver.go
cli/daemon/process.go
cli/daemon/test_process/test_process.go
cli/process_utils/process_utils.go
cli/running/base_instance.go
cli/running/cluster_instance.go
cli/running/cluster_instance_test.go
cli/running/instance.go
cli/running/process_controller.go
cli/running/running.go
cli/running/script_instance.go
cli/running/script_instance_test.go
cli/running/watchdog.go
cli/running/watchdog_test.go
cli/running/writer.go
cli/running/writer_test.go
cli/tail/color.go
cli/ttlog/logger.go
cli/ttlog/logger_test.go
go.mod
go.sum
test/integration/log/test_log.py
test/integration/running/test_running.py
test/utils.py

This patch adds support for `tt start` interactive mode with
`-i/--interactive` flag. In this mode `tt` will wait for
child Tarantool process completions. Standard output will be
used instead of the default log files. Use Ctrl-C combination
to stop `tt` and its child Tarantool instances. No watchdog
processes created.

`tt start` interactive mode

---

.github/workflows/full-ci.yml

There were still tarantool processes running after all tests were completed. After the patch all not killed instances of tarantool will be killed in CI pipeline.

ci: add step with killing tarantool after tests

---

test/integration/cluster/test_cluster_demote.py
test/integration/cluster/test_cluster_expel.py
test/integration/cluster/test_cluster_promote.py
test/integration/cluster/test_cluster_publish.py
test/integration/cluster/test_cluster_show.py
test/utils.py

There were integration tests for `tt cluster replicaset` only for `etcd` and weren't for Tarantool Config Storage.
Due to the same interface tests have been parametrised to do the same business logic for different storages.
Closes #879

replicaset: add tests for tarantool config storage

---

CHANGELOG.md
cli/cmd/root.go
cli/cmd/start.go
cli/cmdcontext/cmdcontext.go
cli/configure/configure.go
cli/rocks/rocks.go
cli/running/running.go
test/integration/rocks/test_rocks.py

It was impossible to provide integrity check period in `tt restart`. After the patch flag "--integrity-check-period" is locating in the global cli context.
Part of https://github.com/tarantool/tt-ee/issues/203

cli: add integrity-check-period flag in global context

---

CHANGELOG.md
cli/cluster/cluster.go
cli/cluster/cmd/replicaset.go
cli/cmd/cluster.go
cli/init/init.go
cli/replicaset/cconfig.go
cli/replicaset/configsource.go
cli/replicaset/configsource_test.go
cli/replicaset/roles.go
test/integration/cluster/test_cluster_roles_add.py

Title: `tt cluster rs roles add` adds role in config scope provided by flags.
This patch introduces new command for the cluster replicaset module:
```
tt cluster replicaset roles add <URI> <ROLE_NAME> [flags]
```
URI is a target configuration source (etcd/tcs). ROLE_NAME is a role for adding to a Tarantool config storage. It is necessary to provide flag with destination in config for role addition. It can be one or more roles.
Command supports following flags:
- Flags for the destination of role addition:
- `--global (-G)` for a global scope to add a role;
- `--instance (-i) string` for an application name target to specify an instance to add a role;
- `--replicaset (-r) string` for an application name target to specify a replicaset to add a role;
- `--group (-g) …

cluster: add command 'roles add'

---

CHANGELOG.md
cli/cluster/cmd/replicaset.go
cli/cmd/cluster.go
cli/cmd/help.go
cli/cmd/start.go
cli/connector/connector.go
cli/connector/eval_plain_text.go
cli/daemon/api/http.go
cli/install/install.go
cli/replicaset/cartridge.go
cli/replicaset/cconfig.go
cli/replicaset/configsource.go
cli/replicaset/configsource_test.go
cli/replicaset/roles.go
cli/replicaset/roles_test.go
cli/running/running.go
test/integration/cluster/test_cluster_roles_remove.py

Title: `tt cluster rs roles remove` removes role in config scope provided by flags.
This patch introduces new command for the cluster replicaset module:
```
tt cluster replicaset roles remove <URI> <ROLE_NAME> [flags]
```
URI is a target configuration source (etcd/tcs). ROLE_NAME is a role removing from a Tarantool config storage. It is necessary to provide flag with destination in config for role removing. It can be one or more destinations.
Command supports following flags:
- Flags for the destination of role removing:
- `--global (-G)` for a global scope to remove a role;
- `--instance (-i) string` for an application name target to specify
an instance to remove a role;
- `--replicaset (-r) string` for an application name target to specify
a replicaset to remove a …

cluster: add command 'roles remove' 

---

CHANGELOG.md
cli/cmd/stop.go
test/cartridge_helper.py
test/integration/create/test_create.py
test/integration/daemon/test_daemon.py
test/integration/replicaset/replicaset_helpers.py
test/integration/replicaset/test_replicaset_bootstrap.py
test/integration/replicaset/test_replicaset_demote.py
test/integration/replicaset/test_replicaset_expel.py
test/integration/replicaset/test_replicaset_promote.py
test/integration/replicaset/test_replicaset_rebootstrap.py
test/integration/replicaset/test_replicaset_roles_add.py
test/integration/replicaset/test_replicaset_vshard.py
test/integration/restart/test_restart.py
test/integration/running/test_running.py
test/integration/running/test_running_cluster.py
test/integration/stop/multi_app
test/integration/stop/test_app.lua
test/integration/stop/test_stop.py
test/vshard_cluster.py

Since the **stop** command is dangerous and can be harmful if executed accidentally, it was necessary to add a user confirmation for its execution to improve security.  
To use auto-confirm, you must pass the -y / --yes option, like this: `tt stop -y` or you can use `--no-prompt` option to skip interactions.

stop:added confirmation

---

CHANGELOG.md
cli/cluster/cmd/replicaset.go
cli/cmd/cluster.go
cli/cmd/replicaset.go
cli/replicaset/cartridge.go
cli/replicaset/cartridge_test.go
cli/replicaset/cconfig.go
cli/replicaset/cconfig_test.go
cli/replicaset/cmd/common.go
cli/replicaset/cmd/roles.go
cli/replicaset/configsource.go
cli/replicaset/configsource_test.go
cli/replicaset/custom.go
cli/replicaset/custom_test.go
cli/replicaset/roles.go
cli/replicaset/roles_test.go
cli/running/running.go
test/cartridge_helper.py
test/integration/replicaset/test_replicaset_bootstrap.py
test/integration/replicaset/test_replicaset_roles_remove.py

Title: `tt replicaset roles remove` removes roles in the tarantool replicaset
with cluster config (3.0) or cartridge orchestrator.
This patch introduces new command for the replicaset module.
```
$ tt rs roles remove [--cartridge|--config|--custom] [-f] [--timeout secs]
<APP_NAME:INSTANCE_NAME> <ROLE_NAME> [flags]
```
It is possible to provide `cartridge`, `config` or `custom` flag to explicitly state which orchestrator to use. ROLE_NAME is a role to remove from local cluster config in case of `cluster config` orchestrator and directly from all instances of replicaset in case of `cartridge` orchestrator. Command supports `cartridge` and `cluster config` orchestrators only for the entire application. INSTANCE_NAME works only for `cluster config` to provide instance …

replicaset: add command 'roles remove'

---

test/integration/replicaset/test_replicaset_roles_remove.py

Since `stop` command needs confirmation by default, new tests was failed waiting indefinitely for confirmation.
After the patch `stop` is executed with `-y` flag to ignore the confirmation request.
Follow up #916

test: fix stop without prompt

---

.github/workflows/full-ci.yml
.github/workflows/tests.yml
cli/running/process_controller.go
cli/running/script_instance_test.go
test/integration/rocks/test_rocks.py
test/integration/running/test_running.py

There are a few failed tests with replacing tarantool sdk version in CI workflow from 3.0.0 into 3.2.0.
After the patch all failed tests related with the upgrade was fixed.
Part of https://github.com/tarantool/tt/issues/931

ci: fix failed tests with tarantool 3.2.0

---

CHANGELOG.md
cli/tail/tail.go
test/conftest.py
test/integration/log/test_log.py

- `tt log -f` crashes if the log directory is removed:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe6dbf9]
```
Perform graceful shutdown in case of inability to continue following the log.
- Provide a way to disable static openssl linking for tests.

Fix tt log follow segmentation fault

---

CHANGELOG.md
cli/connect/commands.go
cli/connect/console.go
cli/connect/const.go
cli/connect/input.go
cli/connect/input_test.go
test/integration/connect/test_connect.py

The “\set delimiter [marker]” command is handled by the `tt` utility, simulating the behavior of a similar command for the Tarantool console.
Closes #727

tt: add support set delimiter in console

---

.github/workflows/full-ci.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
.github/workflows/update.yml
CHANGELOG.md
cli/install/install.go
cli/uninstall/uninstall.go
cli/uninstall/uninstall_test.go
cli/version/version_match.go
cli/version/version_match_test.go
cli/version/version_tools.go
go.mod
test/integration/install/test_install.py

Allow specify version like:
- 2.11 - Chooses last release patch for specified major.minor set
- 3 - get last available release version with required major==3
- 2.11-rc - will select in major.minor version with last release candidate mark
And many other combination matched with version regular expression.
Closes #737

install: add the ability to flexibly define the version

---

.github/actions/prepare-ce-test-env/action.yml
.github/actions/prepare-ee-test-env/action.yml

Fixed CI environment setup with required Python version.
Follows up #727

ci: fix Python version for tests

---

CHANGELOG.md
cli/connect/connect.go
test/integration/connect/test_connect.py

We did not check the response size, which may lead to a crash due to an index out of range.
Closes #964

connect: fix crash due to an empty response

---

CHANGELOG.md
cli/cmd/status.go
cli/status/lua/instance_state.lua
cli/status/status.go
test/integration/status/single_app/init.lua
test/integration/status/test_custom_app/init.lua
test/integration/status/test_status.py
test/utils.py

This patch improves the `tt status` command by displaying all collected errors, warnings, and the current instance status. Instances with warnings or errors will now be highlighted in yellow.
Closes #836

tt status: print detailed alerts for instances

---

test/integration/connect/test_connect.py

Wrap call `start_app` & `stop_app` in try/finally blocks. Modified code was auto reformatted, also.
Closes #956

test: update test_connect to use stop_app

---

cli/running/base_instance.go
test/integration/run/test_run.py

If tarantool executable is not found, `tt run` prints "open : no such file or directory" error, which is confusing. Make the error message more clear.
Closes #966

run: fix confusing error message for tt run

---

CHANGELOG.md
lib/cluster/cluster.go
lib/cluster/cluster_test.go

This patch fixes an incorrect SSL certificate parameter name.
Closes #938

start: fix start Tarantool 3 with encrypted etcd

---

CHANGELOG.md
cli/cmd/replicaset.go
cli/replicaset/lua/cconfig/bootstrap_vshard_body.lua

The `--timeout` flag for `tt vshard bootstrap` is now passed as `vshard.router.bootstrap({timeout=...})`. It allows to increase the real bootstrap process timeout.
Closes https://github.com/tarantool/tt-ee/issues/232
I also noticed that the default timeout was 3 seconds instead of 10s expected. Fixed.

replicaset: use `vshard bootstrap` timeout as bootstrap timeout

---

go.mod
go.sum

Update package go-prompt with fix crash on update completions.
Closes #944

build(deps): bump github.com/tarantool/go-prompt

---

.github/workflows/full-ci.yml
.github/workflows/tests.yml
cli/connector/integration_test.go
cli/replicaset/integration_test.go

This PR fixes CI problems appeared in jobs on machine with `macOS`. There are problems provided below that was fixed.
> There was a problem on macOS pipeline that integration tests written on Go fail sometimes with an `connection refused` error. An instance of Tarantool was unable to start with the specified configuration.
>
>After the patch start options such as `WaitStart`, `ConnectionRetry` and `RetryTimeout` were increased to have enough time for Tarantool startup.
> Sometimes CI on macos fails with an error "docker daemon not running".
>
> To avoid it after the patch docker socket is provided in the github env directly.
>The test `test_t3_instance_names_no_config` always fails because of very long path in tmpdir. This test requires socket path with fexed length, otherwise it can …

ci: fix macos tests

---

magefile.publish.go

We have a `tt` package in the `linux-deb/static` repository and it is suitable for Ubuntu Noble as well. However, sometimes it is convenient to have the same focal/jammy/noble setup, where the `ubuntu/${codename}` repository is enabled.

cd: add Ubuntu Noble

---

CHANGELOG.md
test/integration/running/test_running.py

Added a number of subcommands for replicaset roles, improved understanding of the version number to install, enhanced status display, and added a flag to disable interactivity when the application is stopped.
Implemented a number of fixes to improve stability.
- `tt status`: display `config`, `box`, and `replication upstream` statuses.
* `--details`: display detailed reports of errors and warnings from instances.
- `tt stop` confirmation prompt. `-y` option is added to accept stop without prompting.
- `tt cluster replicaset roles add`: command to add roles in config scope provided by flags.
- `tt replicaset roles remove`: command to remove roles in the tarantool replicaset with cluster config (3.0) or cartridge orchestrator.
- `tt replicaset roles add`: command to add roles in the …

Release 2.5.0

---

CHANGELOG.md

There is missing `tt cluster replicaset roles remove` changelog entries, but duplication of `tt replicaset roles remove`.

changelog: fix `tt replicaset roles remove` duplication

---

CHANGELOG.md
goreleaser/.goreleaser_linux.yml
goreleaser/.goreleaser_linux_arm64.yml
goreleaser/.goreleaser_macOS.yml

It is already done for local builds [1], but we forgot to do it for the goreleaser builds on CI.
1. https://github.com/tarantool/tt/pull/891
Part of https://github.com/tarantool/tt-ee/issues/243

build: add go_tarantool_msgpack_v5 tag to goreleaser

---

lib/cluster/go.mod
lib/cluster/go.sum

Bump github.com/golang/protobuf to v1.5.4 to fix unit tests build.

deps: bump google.golang.org/protobuf

---

test/integration/running/test_running_cluster.py
test/utils.py

The integration test `test_running_cluster::test_running_base_functionality` fails sometimes with an failed assertion of the same PID after restart.
After the patch waiting for instances stop was added to make sure that cluster is down before it will start again and will check for PID.
Closes #972

tests: fix flacky test_running_base_functionality

---

CHANGELOG.md

Small fixes and update MessagePack library.
- Release packages were built using the outdated and buggy MessagePack
library.

Release 2.5.1

---

cli/rocks/extra/hardcoded.lua
cli/rocks/rocks.go
test/integration/rocks/test_rocks.py
test/utils.py

Updated luarocks dependency to 3.10.
And there were a problem - rocks used Lua as an interpreter instead of Tarantool if it found users config. So now rocks  always uses tarantool as an interpreter
Closes #919

rocks: fix wrong interpreter after install

---

.github/workflows/full-ci.yml
.github/workflows/tests.yml
.github/workflows/update.yml
go.mod
go.sum

The latest version fixes a svacer issues.

deps: bump go-openssl to v1.1.1

---

CHANGELOG.md

Update luarocks and libraries version.
- Release packages were built using the outdated and buggy MessagePack
library.

Release 2.5.2

---

test/integration/running/test_running_cluster.py
test/utils.py

The problem occurs when trying to stop cluster (either with `tt stop` or with `tt restart`) at the moment bootstrap have not been completed. In such a scenario once the replica instance is stopped with either of the mentioned commands the corresponding master instance exits instantly with the critical failure as below:
```
F> can't initialize storage: Can't check who replica <...> at <...> chose its bootstrap leader
```
As a result `tt stop/restart` for the master instance doesn't produce the termination-message:
```
The Instance small_cluster_app:storage-master (PID = <...>) has been terminated
```
because such kind of message is produced only for a running instance.
This commit introduces waiting for the cluster bootstrap completion after it is started or restarted.
Closes #1000

tests: fix flaky tests in test_running_cluster.py

---

CHANGELOG.md
cli/rocks/rocks.go
test/integration/rocks/test_rocks.py

It also bumps a commit on the branch and fixes an loading of local configs.
Fixes https://github.com/tarantool/tt/issues/1003

rocks: revert to 3.9.2

---

CHANGELOG.md
cli/cmd/replicaset.go
cli/replicaset/cmd/lua/upgrade.lua
cli/replicaset/cmd/status.go
cli/replicaset/cmd/upgrade.go
test/integration/replicaset/single-t2-app/init.lua
test/integration/replicaset/single-t2-app/tt.yaml
test/integration/replicaset/test_replicaset_upgrade.py

- For each replicaset:
- On the master instance:
1. Execute the following commands sequentially:
```lua
box.schema.upgrade()
box.snapshot()
```
- On each replica:
1. Wait until the replica applies all transactions produced by `box.schema.upgrade()` on the master by comparing the vector clocks (vclock).
2. Once synchronization is confirmed, execute the following command on the replica:
```lua
box.snapshot()
```
> If any errors occur during the upgrade process, the process will stop and an error report will be generated.
-----
The replica is waiting for synchronization for `Timeout` seconds. The default value for `Timeout` is 5 seconds, but you can specify it manually using the `--timeout` option.
```bash
$tt upgrade [<APP_NAME>] --timeout 10
```
You can also specify which replicaset(s) to …

tt: add command `tt upgrade`

---

.github/workflows/full-ci.yml
.github/workflows/tests.yml

It was decided to turn off macOS on CI until we provide a good support.

ci: disable run on macOS

---

CHANGELOG.md

The patch fixes formatting in the CHANGELOG.md. The key changes:
- Formatting of indents for lists has been unificated.
- A maximum line length is limited to 80 characters except links.
- The release overviews have been rewritten a bit to make them look better.
In addition, several non-critical corrections were made.

changelog: fix formatting

---

CHANGELOG.md
cli/cfg/dump_test.go
cli/config/config.go
cli/configure/configure.go
cli/configure/configure_test.go
cli/configure/testdata/modules_cfg/tt-modules1.yaml
cli/configure/testdata/modules_cfg/tt-modules2.yml
cli/configure/testdata/modules_cfg/tt-modules3.yaml
cli/configure/testdata/modules_cfg/tt-modules4.yml
cli/configure/testdata/modules_cfg/tt-modules5.yaml
cli/init/init.go
cli/init/init_test.go
cli/init/templates/tt.yaml.default
cli/modules/modules.go
cli/pack/common.go
cli/pack/common_test.go
cli/util/util.go
test/integration/cfg/test_dump.py
test/integration/init/test_init.py

Closes #1012
Title: Allow multiple directories with modules
The logic of working with configuration file tt.yaml has been updated,
now  modules/directory can be specified both as a single line and
as a list.
**Usage example**
Old behavior:
```yaml
modules:
directory: modules
```
Possibility to specify a list of directories:
```yaml
modules:
directory:
- modules
- /ext/path/modules
- other_modules
```
If a relative path is specified, the search is performed in
the subfolders below, relative to the tt.yaml file. If an absolute
path is specified, external modules are searched according to
the specified path.

modules: tt.yaml modules/directory support list

---

CHANGELOG.md
cli/cmd/replicaset.go
cli/replicaset/cmd/downgrade.go
cli/replicaset/cmd/lua/downgrade.lua
test/integration/replicaset/test_replicaset_downgrade.py

The `tt replicaset downgrade` command works similarly to `tt replicaset upgrade` (see https://github.com/tarantool/doc/issues/4641, https://github.com/tarantool/doc/issues/4661) but requires specifying a target version for the downgrade and uses `box.schema.downgrade(<..version..>)` instead of `box.schema.upgrade()`.
The version must be provided using the `--version` (or `-v`) option in the `x.x.x` format, where `x` represents a numerical value.
```bash
$ tt replicaset downgrade [<APP_NAME> | <URI>] --version 3.0.0
```
Can only be used with tarantool `>= 2.11`.
>The 2.11 version provides the ability to downgrade a database to the specified Tarantool version using the [box.schema.downgrade()](https://www.tarantool.io/ru/doc/latest/reference/reference_lua/box_schema/downgrade/#box-schema-dow …

`tt replicaset`: add subcommand downgrade

---

cli/install/Dockerfile.tnt.build

It required to build Tarantool 3.3 in Docker.
Closes #1046

test: update CMake in Dockerfile's template

---

cli/cmd/logrotate.go
cli/running/running.go
test/integration/logrotate/test_logrotate.py
test/integration/running/test_running.py

Just warn that the instance is not running and continue (like `tt stop` or `tt kill` do).
Closes #774

logrotate: don't exit at non-running instance

---

CHANGELOG.md
cli/modules/modules.go
cli/modules/modules_test.go

Closes #1013 
Title: Use environment variable to find modules.
The TT_CLI_MODULES_PATH environment variable specifies a list of
module's paths separated by a colon “:”.
It can be set externally from tt and must contain a list of
folders where modules are located.
The logic of working with this variable is similar to the PATH
system variable.
Lists of modules are combined into one common list:
- The modules declared in the configuration file tt.yaml come first
- then the modules defined via the environment variable are added.
Any duplicates must be removed, while maintaining the original
order of module declarations.
**Usage example**
Set variable:
```sh
export TT_CLI_MODULES_PATH=/ext/path/modules:${TT_CLI_MODULES_PATH}
```

modules: find module with TT_CLI_MODULES_PATH

---

.github/actions/prepare-ce-test-env/action.yml
.github/actions/prepare-ee-test-env/action.yml
.github/workflows/full-ci.yml
CHANGELOG.md
cli/cmd/coredump.go
cli/coredump/coredump.go
cli/coredump/scripts/tarabrt.sh
test/integration/coredump/test_coredump.py
test/utils.py

`-e,--executable path`  Tarantool executable path
`-p,--pid pid`   PID of the dumped process
`-t,--time time`  Time of dump (seconds since the Epoch)
Closes #763

coredump: support options in `pack` subcommand

---

CHANGELOG.md
cli/cmd/coredump.go
test/integration/coredump/test_coredump.py

Closes #1069
Title: `tt coredump pack` first search tarantool executable in tt env

coredump pack: use tt env if omitted `-e` flag

---

.github/actions/static-code-check/action.yml

This patch locks `golangci-lint` version at 1.62.2.
Closes #1079

lint: golangci-lint version lock

---

.gitmodules

Use HTTPS instead Git protocol to avoid extra authorization.

aeon: fix repo URL for Aeon submodule

---

cli/uninstall/uninstall.go
test/integration/uninstall/test_uninstall.py

uninstall: fix uninstalling if no symlink in bin_dir

---

CHANGELOG.md
cli/aeon/client.go

System certificates must be used unless the user specifies a custom one.
Closes #1049

aeon: load system CAs by default

---

.github/workflows/publish.yml
lib/cluster/collector.go
lib/cluster/collector_test.go
lib/cluster/datacollector.go
lib/cluster/datapublisher.go
lib/cluster/tarantool.go

Using Doer instead of Connector allows us to use
the NewMockDoer helper for Unit tests.

cluster: use tarantool.Doer interface

---

CHANGELOG.md
cli/cmdcontext/cmdcontext.go
cli/configure/configure.go
cli/pack/common.go
cli/pack/common_test.go
test/integration/pack/test_pack.py

pack: added TCM file packaging
Closes #TNTP-1097

pack: added TCM file packaging

---

.github/workflows/publish.yml

Since we don't support a build without OpenSSL it is required always to specify paths to the compiled OpenSSL to build a tt with it.

ci: fix publish on arm64

---

.github/workflows/publish.yml

1. https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

ci: bump download-artifact action

---

CHANGELOG.md
cli/connect/internal/luabody/eval_func_body.lua
test/integration/connect/test_connect.py

close #1064
solution emulation on version 2.7.0 by evaler
```
echo "hello)" | tt connect --evaler '_, errmsg = loadstring(cmd); box.error(box.error.PROC_LUA,  errmsg)' $TARANTOOL_CONSOLE_URI
---
- error: '[string "hello)"]:1: ''='' expected near '')'''
...
```

connect: fix Lua parse error handling - return instead of ignoring

---

CHANGELOG.md

Entries about Lua parse error was rebased into wrong place.
Follow up #1064

changelog: fix entries about Lua parse error

---

CHANGELOG.md
cli/connect/console.go
test/integration/connect/test_connect.py
test/tt_helper.py

connect: allow to disconnect by `Ctrl+C`/`Ctrl+\` if execution hung

---

magefile.publish.go

It follows up #980 and #987.
I don't know a reason why this change is reverted: what is the problem? Anyway, I hope that it is resolved now. But if not, please, let me know what else I should do.

Reapply "cd: add Ubuntu Noble"

---

CHANGELOG.md
cli/templates/internal/engines/builtin_funcs.go
cli/templates/internal/engines/builtin_funcs_test.go
cli/templates/internal/engines/go_text_engine.go
cli/templates/internal/engines/go_text_engine_test.go

The configuration template generation functionality has been extended:
- Previously, the `{{ port }}` construct was available for generating cluster configuration files with different ports.
- A new construct, `{{ metricsPort }}`, has been added for generating the port of the metrics/metrics-export-role module.
This allows for more flexible configuration of ports for instances.
Based on PR: https://github.com/tarantool/tt/pull/1107

feat: added support for new {{ metricsPort }} construct

---

.codespellrc
CHANGELOG.md
lib/dial/dial_test.go
magefile.go
test/integration/cluster/test_cluster_promote.py
test/integration/replicaset/test_replicaset_expel.py
test/requirements.txt

The release introduces minor changes in stabilization of `tt connect`
command. Expanded possibility to connect to `aeon` base.
Improvement in the work of templates.
- `tt aeon connect`: add connection from the `app:instance_name`.
- Added support for the `{{ metricsPort }}` construct in Go text templates.
This new function allows template users to generate a monitoring port value
directly within their templates, providing more flexibility and simplifying
configuration management.
- `tt connect`: allow to disconnect with `Ctrl+C` or `Ctrl+\` if script execution hung.
- `tt connect`: return Lua parse error.
- `tt connect`: panic on render empty table.
- `tt` can be built without linking to OpenSSL.

Release 2.8.1

---

cli/cmd/aeon.go
cli/cmd/binaries.go
cli/cmd/cat.go
cli/cmd/create.go
cli/cmd/daemon.go
cli/cmd/download.go
cli/cmd/enable.go
cli/cmd/install.go
cli/cmd/pack.go
cli/cmd/play.go
cli/cmd/replicaset.go
cli/cmd/root.go
cli/cmd/search.go
cli/cmd/uninstall.go
cli/create/create.go
cli/download/download.go
cli/install/install.go
cli/util/util.go
cli/util/util_test.go
test/integration/cat/test_cat.py
test/integration/pack/test_pack.py
test/integration/replicaset/test_replicaset_rebootstrap.py

Use Cobra functionality to validate arguments

---

CHANGELOG.md
cli/pack/common.go
cli/pack/ignore.go
cli/pack/ignore_test.go
cli/util/osfs.go
test/integration/pack/test_pack.py

In some cases, there are files that may be useful, but should not be part of artifact. The ability to add files and directories to the .packignore file has been added, which allows you to ignore these files and directories when packing.
Closes #812

pack: support .packignore

---

cli/cmd/aeon.go

It seems some debug trace were left in code. This request removes them.
Related to #1128

aeon: remove forgotten debug traces

---

.github/pull_request_template.md

Currently the line breaks in the list don't look good.
See the problem below:
What has been done? Why? What problem is being solved?
(see [documentation][how-to-write-commit] how to write a commit message)
(see [example][tarantoolbot-example])
Related to #XXX
Part of #XXX
Closes #XXX

github: update PR template

---

test/requirements.txt

After upgrading cmake on CI runners it starts to generate warning during CI tests that finally leads to CI failure.
This patch applies quick fix that uses cmake of an older version to avoid the warning.
Related to #TNTP-1918

ci: hotfix to avoid cmake warning

---

CHANGELOG.md
cli/cmd/root.go
cli/configure/configure.go
test/integration/version/test_version.py

Arguments of an internal command are not parsed if it is forced over its existent external counterpart.
Closes #1134 

Fix arguments parsing if internal command is forced over external

---

.github/workflows/publish.yml

Special job was added to avoid publishing release with a tag that is not visible from the master branch. Such a tag produces `tt` that displays incorrect version information with `tt version`
Closes #TNTP-1826

ci: add release tag validation

---

.github/workflows/publish.yml

This patch turns back building of the packages that should be triggered by push event on master branch and that was turned off by mistake with the previous patch.
Related to #TNTP-1826

ci: restore packages build on master push

---

CHANGELOG.md
cli/cmd/completion.go
cli/cmd/help.go
cli/cmd/modules.go
cli/cmd/root.go
cli/modules/modules.go
cli/modules/modules_test.go
cli/modules/run.go
cli/modules/testdata/bad_manifest/no_version/main
cli/modules/testdata/bad_manifest/simple/main
cli/modules/testdata/disabled_override/modules/main
cli/modules/testdata/mod_override/testCmd/main
cli/modules/testdata/modules1/simple/main

It's part of `modules` support. Introduce `modules list` sub-command.
(see [documentation][how-to-write-commit] how to write a commit message)
(see [example][tarantoolbot-example])
Closes #1016
Closes #TNTP-1805

modules: add command to list modules

---

CHANGELOG.md
cli/cmd/aeon.go
test/integration/aeon/test_aeon.py

What has been done? Why? What problem is being solved?
Related to #XXX
Part of #XXX
Closes #XXX

aeon: Fix SSL paths configuration for aeon connection

---

CHANGELOG.md
cli/pack/rpm_header.go
test/integration/pack/test_pack.py

Closes #1143
@TarantoolBot
Title: Fix packing rpm if only one of --pre/postinst option is specified

pack: fix packing rpm if only one of --pre/postinst option specified

---

cli/pack/deb.go

Handle 'debBin' is created at deb.go:186 by calling function 'os.Create' and lost at deb.go:192.

svacer: fix handle leaks

---

lib/connect/go.mod
lib/integrity/go.mod

This patch bumps `go` version for internal packages `lib/connect` and `lib/integrity`.

go: bump version to v1.23.8

---

cli/init/init.go
cli/modules/modules_test.go
cli/pack/common.go
test/integration/cli/test_launch.py
test/integration/help/test_help.py
test/integration/modules/test_modules_list.py
test/integration/version/test_version.py
test/module.py.tt
test/utils.py

Restore working integration tests for external modules.
Closes #TNTP-1809

test: turn on integration tests for modules

---

CHANGELOG.md
cli/aeon/client.go

Fixed a crash in `tt aeon connect` when processing responses from certain SQL commands.
Closes #TNTP-2413

aeon: fix crash on SQL response parsing

---

CHANGELOG.md
cli/checkpoint/checkpoint.go
cli/cmd/cat.go
cli/cmd/play.go
cli/util/util.go
cli/util/util_test.go
cli/util/wal.go
cli/util/wal_test.go
test/conftest.py
test/integration/cat/test_cat.py
test/integration/play/test_play.py

This commit improves the functionality of the `cat` and `play` commands in the Tarantool CLI. It allows these commands to work recursively with directories containing multiple files, enhancing their usability and flexibility.
**Usage Example**:
```bash
tt cat -r /path/to/directory1 /path/to/directory2
tt play --recursive app:instance001 /path/to/directory1
```
Closes #TNTP-2367

play: fix cat/play working with directories

---

CHANGELOG.md
cli/replicaset/cmd/vshard.go
test/integration/modules/test_modules_list.py
test/integration/replicaset/test_replicaset_vshard.py
test/integration/replicaset/test_vshard_app_timeout/config.yaml
test/integration/replicaset/test_vshard_app_timeout/instances.yaml
test/integration/replicaset/test_vshard_app_timeout/router.lua
test/integration/replicaset/test_vshard_app_timeout/storage.lua
test/integration/replicaset/test_vshard_app_timeout/vshard_app-scm-1.rockspec

This commit makes the `timeout` parameter define the duration for `vshard` bootstrapping attemps.
Closes #TNTP-2729

rs: retry to bootstrap vshard within the timeout

---

CHANGELOG.md
cli/checkpoint/lua/play.lua
test/integration/play/test_play.py

This patch extends error message if space to play data is unavailable or user does not have permission to work with it, because the `net.box` module does not have means to distinguish between these errors.
Closes #TNTP-2366

play: extend error message

---

CHANGELOG.md
cli/running/base_instance.go
cli/ttlog/logger.go
test/integration/logrotate/test_logrotate.py

Watchdog launches tarantool in a way that produce log to stderr and thus tarantool itself does nothing to handle log rotation, it is handled entirely at watchdog side.
Prior to this patch `os.File` was used in `Cmd.Stdout`, when watchdog launches tarantool binary and according to golang [documentation](https://pkg.go.dev/os/exec#Cmd) (see `Exec.Cmd.Stdout`) in this special case output from the child process is connected directly to that file. It means that even if it is closed at watchdog side, its child process (tarantool) keeps using the original one, i.e. it proceeds with logging to the original file even after renaming it.
Now `Logger` is used as `Cmd.Stdout`, and according to the mentioned documentation separate goroutine reads output from the child process over a pipe and delivers …

logrotate: fix log rotation

---

test/integration/replicaset/test_replicaset_vshard.py

Sometimes 5 seconds is not enough for `tt rs vs bootstrap --timeout 5` command to finalize. This patch increases this timeout to 10s.
Closes #1176

test: increase timeout for flaky test

---

.github/actions/static-code-check/action.yml

Enable static code checks in the CI pipeline for new code changes.
Closes #TNTP-2939

ci: turn on pre-commit checks for fresh code

---

CHANGELOG.md

The release introduces a fix for the `tt logrotate` command, which now properly
releases the descriptor of the old log file.
Closes #TNTP-3237

Release 2.10.1

---

.github/actions/check-commit-msg/action.yml
.github/workflows/tests.yml

Auto validation on CI for format of commit message.
Closes #TNTP-3712

ci: add auto checks for commit message

---

test/conftest.py
test/integration/create/test_create.py
test/integration/ttbuild/test_build.py
test/utils.py

test: disable config storage tests for Tarantool CE

---

CHANGELOG.md
cli/cmd/create.go
cli/cmd/create_test.go
cli/codegen/generate_code.go
cli/create/builtin_templates/builtin_templates.go
cli/create/builtin_templates/templates/cluster/MANIFEST.yaml
cli/create/builtin_templates/templates/cluster/app.lua
cli/create/builtin_templates/templates/cluster/config.yaml.tt.template
cli/create/builtin_templates/templates/cluster/instances.yaml.tt.template
test/integration/create/test_create.py

Configurable parameters:
- Number of replicasets
- Number of replicas per replicaset
- User name
- Password
<details>
<summary>Example of generated config</summary>
Number of replicasets: 2
Number of replicas per replicaset: 3
User: me
Password: bla-BLA-bla
instances.yaml
```yaml
---
replicaset-001-a:
replicaset-001-b:
replicaset-001-c:
replicaset-002-a:
replicaset-002-b:
replicaset-002-c:
```
config.yaml
```yaml
credentials:
users:
me:
password: 'bla-BLA-bla'
roles: [super]
replicator:
password: 'topsecret'
roles: [replication]
iproto:
advertise:
peer:
login: replicator
replication:
failover: manual
groups:
group-001:
app:
file: 'app.lua'
replicasets:
replicaset-001:
leader: replicaset-001-a
instances:
replicaset-001-a:
iproto:
listen:
- uri: 127.0.0.1:3301
replicaset-001-b:
iproto: …
```

create: add template for non-vshard cluster

---

.github/actions/static-code-check/action.yml

Turn on static code analyzes.
Second part for #1184
Part of #TNTP-3105

ci: turn on linters

---

CHANGELOG.md
cli/replicaset/cconfig.go
cli/replicaset/lua/cconfig/bootstrap_vshard_body.lua
cli/replicaset/lua/cconfig/get_sharding_roles_body.lua
test/conftest.py
test/integration/replicaset/test_replicaset_vshard.py
test/tt_helper.py

Make more invormative error when trying to bootstrap non-vshard cluster with `tt rs vshard bootstrap` command.
Closes #1201

replicaset: more informative error at bootstrap
